### ISSUE TITLE
Duplicate of #439 #562

### ISSUE THREAD

**Issue by crystalg21** [wifiphisher/wifiphisher#609] opened 2017-05-10 06:46 UTC
**Screenshots**: 
https://s2.postimg.org/n6jzjsy7t/Screenshot_at_2017-05-10_02-34-55.png
https://s12.postimg.org/le6p6yq2l/Screenshot_at_2017-05-10_02-49-43.png

**Version**: Wifiphisher 1.3

**Distribution**: Kali Linux 32bit mate

**Description**: I am using a AWUS036NHA and when i start the phishing Wi-Fi with any phishing page, as soon as a client connects to the phishing Wi-Fi it does what is shown in the screenshots. Wifiphisher still works fine, but this annoying text clutters the screen.

**Steps to Reproduce**: Start the phishing Wi-Fi with any phishing page and make a client connect to it and the screen gets filled with error text but wifiphisher still works.

**Comment by blackHatMonkey** [comment] 2017-05-10 17:33
@crystalg21 
The first error is a duplicate of #439.
The second error is a duplicate of #562.

Please continue the discussion over there :smile: .

**Closed** 2017-05-10 17:33 UTC
Labels: duplicate

**Comment by crystalg21** [comment] 2017-05-10 17:43
Ok, sorry
