### ISSUE TITLE
don't work in Lubuntu

### ISSUE THREAD

**Issue by cooldang** [wifiphisher/wifiphisher#468] opened 2017-02-25 07:57 UTC
in Kali work well,
but in Lubuntu, phone and computer connect to the fake AP fail.

wireless card and driver:
wlp1s0                     -     Atheros AR9285   -  ath9k
wlx000f13190965    -     RT2870/RT3070    -  rt2800usb

step1.

```
root@je-virtual-machine:/home/je# wifiphisher
[*] Starting Wifiphisher 1.2GIT at 2017-02-25 15:06
wlx000f13190965
enp6s0
lo
wlp1s0
[+] Selecting wlx000f13190965 interface for the deauthentication attack
[+] Selecting wlp1s0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
```

step2.
```
[+] Ctrl-C at any time to copy an access point from below
num  ch   ESSID                   BSSID                encr            vendor
-----------------------------------------------------------------------------
 1 - 4   - DIRECT-NIJESSEPCmsZO  - 5c:f3:70:0c:ba:38 - WPA2         -  CC&C Technologies
 2 - 4   - ZTE                   - e4:77:23:a4:dc:86 - WPA2/WPA     -  zte
 3 - 6   - Tenda_19BD08          - c8:3a:35:19:bd:08 - WPA2/WPA     -  Tenda Technology
^C
[+] Choose the [num] of the AP you wish to copy: 2
```

step3.

```
[+] Choose the [num] of the scenario you wish to use: 1
[+] Selecting Network Manager Connect template
[*] Starting the fake access point...
```
![88](https://cloud.githubusercontent.com/assets/4197820/23329427/0e09c44a-fb73-11e6-9286-9d90779bac11.png)

phone and computer connect to the fake AP fail.

finish,erro

```
[*] ZTE set up on channel 4 via wlx000f13190965 on wlp1s0
[*] Starting HTTP/HTTPS server at ports 8080, 443
[*] Monitor mode: wlx000f13190965 - 00:0f:13:19:09:65
[+] Captured credentials:
Exception in thread Thread-3:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 546, in channel_hop2
    deauth(monchannel)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 605, in deauth
    count=int(args.deauthpackets))
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 258, in send
    realtime=realtime, return_packets=return_packets)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 236, in __gen_send
    s.send(p)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 397, in send
    self.outs.sendto(sx, sdto)
error: [Errno 100] Network is down

[!] Closing
root@je-virtual-machine:/home/je# 
```

iwconfig
```
root@je-virtual-machine:/home/je# iwconfig
wlx000f13190965  IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=20 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:on
          
enp6s0    no wireless extensions.

lo        no wireless extensions.

wlp1s0    IEEE 802.11  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=15 dBm   
          Retry short limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off



```

**Comment by Splinter0** [comment] 2017-02-25 12:53
Sometimes doesn't work for me as well on ubuntu 16.04, but then i found that if u put the card in monitor mode before starting the script, then it works ( for example using airmon-ng ). Try and see if it works
@cooldang

**Comment by cooldang** [comment] 2017-02-25 14:28
@Splinter0 
I try, but don't work.

```
Jamming devices: 
[*] e4:77:23:a4:dc:86 - 80:ed:2c:3c:e0:dc - 4
[*] a4:44:d1:53:7e:41 - e4:77:23:a4:dc:86 - 4  - ZTE
[*] d8:49:2f:89:4a:ea - e4:77:23:a4:dc:86 - 4  - ZTE
[*] e4:77:23:a4:dc:86 - 04:69:f8:0b:45:c3 - 4  - ZTE
[*] e4:77:23:a4:dc:86 - 4  - ZTE

DHCP Leases: 
^CTraceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 978, in run
    proc = check_output(['cat', '/var/lib/misc/dnsmasq.leases'])
  File "/usr/lib/python2.7/subprocess.py", line 567, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1329, in _execute_child
    _close_in_parent(c2pwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1221, in _close_in_parent
    os.close(fd)
OSError: [Errno 9] Bad file descriptor
[!] Failed to reset interface
[!] Closing
root@je-virtual-machine:/home/je/下载/wifiphisher-master/bin# 
```

**Comment by cooldang** [comment] 2017-02-26 11:31
@sophron

**Comment by blackHatMonkey** [comment] 2017-02-26 18:44
Hi @cooldang I will take a look at the bug and see what I can do :smile:.

**Comment by alternatexp** [comment] 2017-02-27 14:17
Please get in the habit of hiding MAC addresses in your posts for privacy reasons.

**Comment by sophron** [comment] 2017-03-05 00:14
Hi @cooldang,

From what I see on your latest paste, you pressed Ctrl + C. The error was because file could not close. It shouldn't interfere with the main program though.

**Comment by blackHatMonkey** [comment] 2017-03-15 15:02
@cooldang Can you try with the latest version and see if the problem is still present?

**Comment by Splinter0** [comment] 2017-03-16 17:23
@blackHatMonkey same as #483

**Comment by blackHatMonkey** [comment] 2017-03-16 17:26
@Splinter0 Thanks. I was looking at [this](https://github.com/wifiphisher/wifiphisher/issues/468#issuecomment-282487321) comment but you are correct.

**Comment by blackHatMonkey** [comment] 2017-03-16 17:27
@cooldang I'm closing this thread because there are more information in #483. Please continue the discussion over there.

**Closed by blackHatMonkey** 2017-03-16 17:27 UTC
Labels: bug: need confirmation
