### ISSUE TITLE
Network is Down

### ISSUE THREAD

**Issue by phspade** [wifiphisher/wifiphisher#714] opened 2017-08-22 05:59 UTC
everytime i run wifiphisher, my network-manager is always down. thou i dont know if my wifiphisher is an outdated because it doesnt have -v to view version or --update to update my wifiphisher :(

after my network-manager is down. i simpley command `sudo service network-manager restart`
and it will go back my wifi..
However, still i cant use wifiphisher properly.

**Comment by anakin1028** [comment] 2017-08-22 06:16
What problem do you have for using wifiphisher? Can you post the output for the following command under the wifiphisher directory?
`git rev-parse HEAD`

**Comment by phspade** [comment] 2017-08-22 12:30
WTF.. it's fix.. But anyways, how to trouble shoot it once i encounter it again? (just in case).

**Comment by anakin1028** [comment] 2017-08-22 12:35
We don't know what problem do you have.

If the problem is that NetworkManager is killed, this is an expected result from the current program since we cannot let the NetworkManager interfere with our jamming and AccessPoint adapters.

**Comment by phspade** [comment] 2017-08-22 12:37
Yeah i encounter earlier the "Network Manager is down".. i dont know and it automatically fixed.. :( 
Anyways ill let you know.. if i encounter it again and i will send a screenshot..

**Comment by anakin1028** [comment] 2017-08-22 12:42
@phspade ok. I will close this issue first if you have the problem again, feel free to reopen it : )

**Closed by anakin1028** 2017-08-22 12:42 UTC
Labels: Needs more information

**Comment by phspade** [comment] 2017-08-24 08:59
yeah sure @anakin1028
