### ISSUE TITLE
Error  message

### ISSUE THREAD

**Issue by wermaxta** [wifiphisher/wifiphisher#766] opened 2017-09-29 08:41 UTC
HI i get this error message my OS is Kali linux Linux 
kali 4.12.0-kali2-amd64 #1 SMP Debian 4.12.12-2kali1 (2017-09-13) x86_64 GNU/Linux
Thank you :)

```
root@kali:~/stuff/wifiphisher/bin# python wifiphisher
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-09-29 11:36
[+] Selecting wlan0 interface for the deauthentication attack
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:02:b6:63
[+] Changing wlan0 MAC addr to 00:00:00:84:5a:bd
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "wifiphisher", line 17, in <module>
    
  File "/root/stuff/wifiphisher/wifiphisher/pywifiphisher.py", line 716, in run
    engine.start()
  File "/root/stuff/wifiphisher/wifiphisher/pywifiphisher.py", line 565, in start
    self.network_manager.up_interface(mon_iface)
  File "/root/stuff/wifiphisher/wifiphisher/common/interfaces.py", line 452, in up_interface
    pyw.up(card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 572, in up
    if iosock is None: return _iostub_(up, card)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 2217, in _iostub_
    return fct(*argv)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 577, in up
    _flagsset_(card.dev, _setf_(flags, ifh.IFF_UP), iosock)
  File "/usr/local/lib/python2.7/dist-packages/PyRIC-0.1.6.3-py2.7.egg/pyric/pyw.py", line 1926, in _flagsset_
    raise pyric.error(e.errno, e.strerror)
pyric.error: [Errno 132] Operation not possible due to RF-kill
```

Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by blackHatMonkey** [comment] 2017-09-29 12:30
@wermaxta This is a duplicate of #592. You can fix this following [this](https://github.com/wifiphisher/wifiphisher/issues/592#issuecomment-299223404).

**Closed by blackHatMonkey** 2017-09-29 12:30 UTC
