### ISSUE TITLE
Captive portals aren't displayed when using a specific wifi usb adapter

### ISSUE THREAD

**Issue by Giova84** [wifiphisher/wifiphisher#853] opened 2018-01-26 01:46 UTC
I’m running Kali Linux (Linux kali 4.14.0-kali3-amd64 # 1 SMP Debian 4.14.12-2kali2 (2018-01-11) x86_64 GNU/Linux) and tried wifiphisher v1.3, 1.4 and from the latest available commit a6478a3938fb0e6a0b4b6fc71ccc4d079cb6c0e8

The usb wifi adapter which I’m using is a TP LINK TL WN722N , (V 1.10)  which works fine by using other utilities (airmon suite), except with wifiphisher, let me explain:

I test it on my own WLAN: the devices are properly de-authenticated, and then will appear the alert which should bring to the captive portal (wifi_connect), but all that I get are 404 error messages (the phishing scenario is not displayed at all), as shown in the following screenshots:

![screenshot_20180126-005500](https://user-images.githubusercontent.com/3594780/35421302-bdcb5b74-0242-11e8-9c1f-7b3074e69e44.png) ![screenshot_20180126-010349](https://user-images.githubusercontent.com/3594780/35421309-c3167f28-0242-11e8-9fb6-f678d6936f66.png)

Seems a problem with TL WN722N wifi adapter, since if I use another adapter (D-Link Corp. DWA-121 802.11n Wireless N 150 Pico Adapter [Realtek RTL8188CUS]) everything works as expected.

Let me know what else I can provide/test/check.

**Comment by Giova84** [comment] 2018-01-26 11:29
I forget to mention the fact that another tool (fluxion) is properly able to generate/shows the captive portal by using TL WN722N wifi adapter.

**Comment by anakin1028** [comment] 2018-01-26 11:58
The phishing page is not relevant to the adaptor. Can you try to use the TPLink adaptor again and post the sniffer on the rogue AP interface?

**Comment by Giova84** [comment] 2018-01-26 12:22
> post the sniffer on the rogue AP interface

Sorry, I'm not very able, sometimes, to properly understand english: what I have to do exactly?

**Comment by anakin1028** [comment] 2018-01-26 12:42
Can you post all the standard out log on the terminal?
You can use the following command after lunching wifiphisher:
`wireshark` and select the AP wlan interface to sniff the frames on that interface like the following link
https://www.google.com.tw/amp/s/www.howtogeek.com/104278/how-to-use-wireshark-to-capture-filter-and-inspect-packets/amp/

**Comment by Giova84** [comment] 2018-01-26 12:59
Done.
[wifiphisher_capture.zip](https://github.com/wifiphisher/wifiphisher/files/1667757/wifiphisher_capture.zip)

However, today, another issue was present: the client didn't auto-connect to the rogue AP, so I manually selected the rogue AP on the device, and this time the captive portal didn't appeared at all.

**Comment by anakin1028** [comment] 2018-01-26 14:53
I can see your device generate http request to us; however the server doesn't reply to the victim device.
file:///home/anakin1028/%E6%A1%8C%E9%9D%A2/2018-01-26%2022:48:04%20%E7%9A%84%E8%9E%A2%E5%B9%95%E6%93%B7%E5%9C%96.png

The interface you have used to captured is the `monitor` interface and can you use the `ap` interface to capture.
After you lunch the `wifiphisher` you can use `iw dev` to see which wlan interface is AP.
like:
https://miloserdov.org/wp-content/uploads/2017/03/01-1.jpg
The `type` field will show AP.

**Comment by Giova84** [comment] 2018-01-26 16:21
`root@h725:~# iw dev
phy#0
	Interface wlan1
		ifindex 4
		wdev 0x2
		addr 00:00:00:13:af:1b
		type monitor
		txpower 20.00 dBm
	Interface wlan0
		ifindex 3
		wdev 0x1
		addr 00:00:00:8d:0f:04
		ssid TIM-24419573
		type AP
		channel 5 (2432 MHz), width: 20 MHz (no HT), center1: 2432 MHz
		txpower 20.00 dBm`

**Comment by anakin1028** [comment] 2018-01-26 16:26
In this case you can use `wlan0` to start Wiesbaden since the this interface is used for AP.

**Comment by anakin1028** [comment] 2018-01-26 16:26
Typo: to start wireshark

**Comment by Giova84** [comment] 2018-01-26 16:36
[wlan0_capture.zip](https://github.com/wifiphisher/wifiphisher/files/1668423/wlan0_capture.zip)

**Comment by anakin1028** [comment] 2018-01-27 13:10
from the sniffer, I can see the victim device generate http request; however rogue AP didn't response to it as the following figure shows:
<img width="1020" alt="2018-01-27 9 02 48" src="https://user-images.githubusercontent.com/6182530/35472197-cd9967f8-03a5-11e8-8a78-f653200b2eaf.png">

There is TCP retransmission from `10.0.0.1` which is the IP address of the rogue AP.
<img width="1182" alt="2018-01-27 9 06 56" src="https://user-images.githubusercontent.com/6182530/35472224-23a1a4b2-03a6-11e8-9141-da92a1725793.png">

And also a lot of arp requests from the end of sniffer and rogue AP doesn't get response from the victim device and this means the traffic from rogue AP to the victim device looks like not connected.
<img width="882" alt="2018-01-27 9 07 07" src="https://user-images.githubusercontent.com/6182530/35472235-465fc614-03a6-11e8-8771-3258e8ee8553.png">

when you get connected can you ping `10.0.0.26` from your linux system?

**Comment by anakin1028** [comment] 2018-01-27 13:11
you can use the following two commands to do test:
```
arping 10.0.0.26
ping 10.0.0.26
```
and see if the connection is connected or not.

**Comment by Giova84** [comment] 2018-01-27 17:26
Ping:

The host is unreachable, and then, after a while (when the captive portal attempts to load) is reachable, and then back again unreachable:

```
root@h725:~# ping 10.0.0.26
PING 10.0.0.26 (10.0.0.26) 56(84) bytes of data.
From 10.0.0.1 icmp_seq=1 Destination Host Unreachable
From 10.0.0.1 icmp_seq=2 Destination Host Unreachable
From 10.0.0.1 icmp_seq=3 Destination Host Unreachable
From 10.0.0.1 icmp_seq=4 Destination Host Unreachable
From 10.0.0.1 icmp_seq=5 Destination Host Unreachable
From 10.0.0.1 icmp_seq=6 Destination Host Unreachable
From 10.0.0.1 icmp_seq=7 Destination Host Unreachable
From 10.0.0.1 icmp_seq=8 Destination Host Unreachable
From 10.0.0.1 icmp_seq=9 Destination Host Unreachable
64 bytes from 10.0.0.26: icmp_seq=10 ttl=64 time=1843 ms
64 bytes from 10.0.0.26: icmp_seq=11 ttl=64 time=1026 ms
64 bytes from 10.0.0.26: icmp_seq=12 ttl=64 time=384 ms
```

Arping:

Doesn't shows anything:

```
[root@h725:~# arping -I wlan0 10.0.0.26
ARPING 10.0.0.26 from 10.0.0.1 wlan0]
```

**Comment by anakin1028** [comment] 2018-01-28 01:03
The connection should be keep connected. Maybe this is the reason why the device doesn't show the phishing page.  For now I have no idea why this happen since I cannot reproduce it by the TPLink WN722N

**Comment by Giova84** [comment] 2018-01-28 02:07
Is your environment on a virtual machine? In my case, maybe, there is some issue with VMware and such wifi adapter?

**Comment by Giova84** [comment] 2018-01-28 17:59
Well, in the meatime I also tried wifi pumpkin, and also his AP (like the one of fluxion) works flawlessly: don't you worry: I'm not saying that wifiphsher is weak (otherwise I would have uninstalled) :-)

**Comment by Giova84** [comment] 2018-01-28 23:42
I have a good news: I updated my system (apt-get update) and now wifiphisher works almost ok; if I give internet access to the AP (using `-iI eth0`) the captive portal is skipped:  clients are able to see any site: I would expect to see the captive portal instead. All is ok if I avoid internet access.

**Comment by anakin1028** [comment] 2018-01-28 23:55
Thanks for your update. There is no captive portal when supply the internet to victims. We may improve this in the future. :)

**Comment by sophron** [comment] 2018-02-11 11:18
I'm closing this, since the new version works fine for the OP.

**Closed by sophron** 2018-02-11 11:18 UTC
Labels: question
