### ISSUE TITLE
Is it possible to make wifiphisher similar with esp8266

### ISSUE THREAD

**Issue by harshil2105** [wifiphisher/wifiphisher#586] opened 2017-04-24 11:11 UTC
is it possible to make wifiphisher spoofing pages with esp8266?

**Comment by JetseVerschuren** [comment] 2017-04-24 11:48
What do you mean? Do you want to ru wifiphisher on  a esp? There is a discussion ongoing on #575.

**Comment by blackHatMonkey** [comment] 2017-04-24 15:44
This is a duplicate of #575. Please continue the discussion there.

**Closed by blackHatMonkey** 2017-04-24 15:44 UTC
Labels: duplicate
