### ISSUE TITLE
getting this error not sure what it is :

### ISSUE THREAD

**Issue by oscarseogod** [wifiphisher/wifiphisher#642] opened 2017-06-15 02:18 UTC
Before opening a new issue, please make sure that what you are about to report has not been reported already. If not, use the following template for reporting.

**Version**: Use `git show | grep commit` command and paste here the output.

**Description**: Give a more analytical description here. The output of the `iw list` and `iwconfig` commands may be helpful.

**Script output**: Paste the output of the tool, including any stack traces.

**Comment by oscarseogod** [comment] 2017-06-15 02:19
Exception in thread Thread-5:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/deauth.py", line 189, in _send_deauthentication_packets
    self._socket.send(packet)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 36, in send
    return self.outs.send(sx)
error: [Errno 100] Network is down

Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/deauth.py", line 127, in _find_clients
    count=1, store=0)
  File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 610, in sniff
    p = s.recv()
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 519, in recv
    pkt, sa_ll = self.ins.recvfrom(x)
error: [Errno 100] Network is down

**Comment by anakin1028** [comment] 2017-06-15 03:12
This looks like a duplicate of #483 
@oscarseogod, let's track on that thread

**Closed** 2017-06-15 03:13 UTC
Labels: duplicate
