### ISSUE TITLE
I get this spam bug during the attack it spams HTTP requests

### ISSUE THREAD

**Issue by VickyTheDon** [wifiphisher/wifiphisher#538] opened 2017-03-23 15:46 UTC
https://drive.google.com/file/d/0B9DJiMZO9ODHN3FDeUZDOS1fcG8/view?usp=sharing

**Comment by blackHatMonkey** [comment] 2017-03-23 15:51
Hi @VickyTheDon please update your original post to include more information.

**Comment by VickyTheDon** [comment] 2017-03-23 16:13
@blackHatMonkey that is the issue

**Comment by blackHatMonkey** [comment] 2017-03-23 16:36
This is a duplicate of #441. The fix is gonna be added soon :smile:. @VickyTheDon Note that you can simply fix it by increasing the height of the terminal.

**Closed by blackHatMonkey** 2017-03-23 16:36 UTC
Labels: duplicate
