### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec

### ISSUE THREAD

**Issue by cooldang** [wifiphisher/wifiphisher#496] opened 2017-03-05 00:22 UTC
Wifiphisher 1.2GIT 
Lubuntu

```bash
root@je-virtual-machine:/home/je# wifiphisher
[*] Starting Wifiphisher 1.2GIT at 2017-03-05 08:16
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 743, in run
    access_point = curses.wrapper(select_access_point, mon_iface)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 462, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_number, position))
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 619, in display_access_points
    access_point.get_number_connected_clients(), vendor))
UnicodeEncodeError: 'ascii' codec can't encode characters in position 0-4: ordinal not in range(128)

```

did i  miss some lib?

**Comment by andeees** [comment] 2017-03-05 01:07
Did you Fake any router's name, which characters are not supported by the ascii?

**Comment by Miayke** [comment] 2017-03-05 13:26
I think these characters do not support the WiFi list, ı, ü, ğ, ö, ş, İ, Ğ, Ü, Ö, Ş, Ç

**Comment by cooldang** [comment] 2017-03-06 01:13
there is a router's name in chinese.

but in Kali Linux everything work well.

**Comment by blackHatMonkey** [comment] 2017-03-07 17:11
@sophron I was able to reproduce this error like so:
```python
ap_name = "鳖宽圭"

try:
    new_name = ap_name.decode("utf8")
except UnicodeDecodeError:
        new_name = "SOMETHING"
screen.addstr(0, 0, new_name)
```

This is what we are doing in `recon` module [L221](https://github.com/wifiphisher/wifiphisher/blob/master/wifiphisher/common/recon.py#L221).

**Comment by blackHatMonkey** [comment] 2017-03-07 17:24
This is @raytafarhan output of the bug which was posted in #503 :
```bash
[*] Starting Wifiphisher 1.2GIT at 2017-03-07 11:57
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 743, in run
    access_point = curses.wrapper(select_access_point, mon_iface)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 462, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_number, position))
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 619, in display_access_points
    access_point.get_number_connected_clients(), vendor))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)
```

**Comment by blackHatMonkey** [comment] 2017-03-07 17:27
@sophron after looking at @raytafarhan output I think the code should be changed to:
```python
name.encode('UTF-8')
```
instead of
```python
name.decode('UTF-8')
```

**Comment by blackHatMonkey** [comment] 2017-03-15 15:11
@cooldang @raytafarhan I pushed some changes [here](https://github.com/wifiphisher/wifiphisher/tree/issue-%23496). If you could try them and let me know if it fixes the issue or not.

**Comment by Miayke** [comment] 2017-03-18 13:41
is bug fixed?

**Comment by raytafarhan** [comment] 2017-03-18 15:24
it fixed after me upgrade os version to kali rolling 2016.2, but i have problems this
"this image was build for another pillow/pil"

**Comment by Miayke** [comment] 2017-03-18 20:31
I've re-established it but it's still closed, it does not support some characters

**Comment by laozi999** [comment] 2017-03-19 01:19
@blackHatMonkey problem persists when I use `-e "鳖宽圭"`

**Comment by sophron** [comment] 2017-03-19 18:14
I just pushed a commit. Please update to the latest revision and let me know if you still have issues.

**Comment by blackHatMonkey** [comment] 2017-03-20 13:29
@laozi999 The problem here is not about creating but rather displaying of the access points.

**Comment by laozi999** [comment] 2017-03-20 20:05
@blackHatMonkey yet they both result in an error

**Comment by blackHatMonkey** [comment] 2017-03-21 13:53
@laozi999 Although I have not tested the `-e` option the problem is with `python 2` `Unicode` handling :cry:.

**Comment by devocator** [comment] 2017-03-25 09:07
when it will be fixed? It gives the error when AP's with blank character in name appears on list.

**Comment by blackHatMonkey** [comment] 2017-04-16 14:13
@cooldang Is this issue present in the latest version or not?

**Closed** 2017-04-24 23:43 UTC
Labels: bug: reproducible, in progress
