### ISSUE TITLE
Errno 105 No Buffer Space Available When Running WifiPhisher

### ISSUE THREAD

**Issue by irnhax** [wifiphisher/wifiphisher#608] opened 2017-05-09 17:11 UTC
**Version**: commit 04c42e25d934f8fcbef6eec81c1ba36423b424cf

**Distribution**: Kali Rolling 2017.1

**Summary**: After initialising the script, I receive the following error:

```
Exception in thread Thread-4:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
    cal/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/deauth.py", line 204, in _send_deauthentication_packets
    self._socket.send(packet)
  File "/usr/lib/python2.7/dist-packages/scapy/arch/linux.py", line 469, in send
    return SuperSocket.send(self, x)
  File "/usr/lib/python2.7/dist-packages/scapy/supersocket.py", line 36, in send
    return self.outs.send(sx)
error: [Errno 105] No buffer space available
```

**Description**: 

When running the script both interactively and specifying command line flags, I receive the "Errno 105 No buffer space available" error. 

This happens on the screen that displays "Deauthenticating Clients", "DHCP Leases" and "HTTP Requests". After the following:

```
[+] Choose the [num] of the scenario you wish to use: 1
[+] Selecting Firmware Upgrade Page template
[*] Starting the fake access point...
[*] Starting HTTP/HTTPS server at ports 8080, 443
[*] Monitor mode: wlan1 - 00:00:00:1b:7a:0b
```

**Steps to Reproduce**: 

Run "wifiphisher"

--

I am using two Alfa AWUS036NEH wifi adapters. 

Any help would be much appreciated. Thanks.

**Comment by blackHatMonkey** [comment] 2017-05-10 12:17
Hi @irnhax thanks for opening an issue.

@sophron @anakin1028  The problem seem to be from the threads and is similar to [this](http://stackoverflow.com/questions/31746401/python-loop-causing-error-errno-105-no-buffer-space-available).

**Comment by anakin1028** [comment] 2017-05-10 14:57
@blackHatMonkey my gut feeling is that we send the packet too fast.
After googling I think we should add some time interval between the frames and catch the error for that
As for mdk3 implementation: it also catch the nobuf error and make the thread sleep.
```c
int send_packet(uchar *buf, size_t count)
{
	struct wif *wi = _wi_out; /* XXX globals suck */
	if (wi_write(wi, buf, count, NULL) == -1) {
		switch (errno) {
		case EAGAIN:
		case ENOBUFS:
			usleep(10000);
			return 0; /* XXX not sure I like this... -sorbo */
		}

		perror("wi_write()");
		return -1;
	}

	return 0;
}
```
Here is also a issue report in scapy as the following link:
[scapy ref](https://bitbucket.org/secdev/scapy/issues/146/outssendto-buffer-problem-on-slow-ppp-link)

@sophron can you also fix this in your new extension manager design? after merge that PR, @irnhax may retest if this is fixed?

**Comment by sophron** [comment] 2017-05-10 17:10
@anakin1028 Yes I'll push a fix in my PR.

@irnhax It should be ready in the next few days.

**Comment by irnhax** [comment] 2017-05-10 23:55
Thanks for the info guys! Sure I'll be able to test early/mid next week.

**Comment by HH-Kh** [comment] 2017-05-11 18:17
I also meet the same problem: 
error [Errno 105] No buffer space available 
It used to work fine in version 1.1GIT for me, but after I upgrade to higher versions (v1.2 & v1.3), I always meet this problem. Waiting for your solution, thanks. 
![image](https://cloud.githubusercontent.com/assets/28632591/25964904/a4969578-36b0-11e7-921f-86823c7144f5.jpeg)

**Comment by anakin1028** [comment] 2017-05-11 23:27
@HH-Kh just wondering what dongle do you use for the jamming interface? Also AWUS036NEH?

**Comment by irnhax** [comment] 2017-06-15 14:45
HI,

Just tested this - getting the same error as before.

**Comment by blackHatMonkey** [comment] 2017-06-15 14:47
@irnhax The fix for this problem has not been pushed out yet. I will update this thread when that happens 😄.

**Comment by irnhax** [comment] 2017-06-23 00:56
@blackHatMonkey ah cool, no worries, thanks! :)

**Comment by anakin1028** [comment] 2017-07-16 12:18
@irnhax the fix has been merged to master. Can you help us to double confirm that the problem is solved?

**Closed** 2017-08-14 14:45 UTC
Labels: bug: reproducible, solved
