### ISSUE TITLE
Duplicate of #439

### ISSUE THREAD

**Issue by piyushx12** [wifiphisher/wifiphisher#1049] opened 2018-12-16 19:44 UTC
![screenshot 2018-11-28 at 9 40 01 pm](https://user-images.githubusercontent.com/38218769/50058021-9cde9380-0198-11e9-8ef9-b2168adeb994.png)
Hello,
I am using Kali linux with two wifi adapters both compatible with Kali. I am getting the above error while using the script, can anyone tell me what this error about and how to fix it. 
Thanks

**Comment by blackHatMonkey** [comment] 2018-12-20 18:25
@piyushx12 Thanks for opening an issue. This seems to a duplicate of #439. If I recall correctly the error can be ignored (I know it is really ugly). We will work on the issue when we have time :smile: .

**Comment by sophron** [comment] 2019-01-18 02:17
Let's continue discussion on #439.

**Closed by sophron** 2019-01-18 02:17 UTC
Labels: duplicate
