### ISSUE TITLE
"Sign into Wi-Fi network" not shown on Android

### ISSUE THREAD

**Issue by totonda** [wifiphisher/wifiphisher#1029] opened 2018-11-06 11:21 UTC
Use the command "wifiphisher --noextensions --essid" FREE WI-FI "-p outh-login -kB". Wi-Fi starts working, but the phishing page does not appear when I connect.
When I connect it says "wifi without internet service"

**Comment by sophron** [comment] 2018-11-06 13:57
There are some typos. I suppose the command you are running is `wifiphisher --noextensions --essid "FREE WI-FI" -p oauth-login -kB`.

**Comment by totonda** [comment] 2018-11-06 14:29
Yes it is. But directly when I connect to the wifi does not appear the phishing page.
I do not know what to do, everything worked well and from one day to the next, wifiphisher stopped working

**Comment by totonda** [comment] 2018-11-06 14:32
For example, When I enter the phone does not say "Access Wi-Fi" and takes me to the login page with Facebook.
Directly connects me to the wifi and tells me that it does not have internet.

**Comment by totonda** [comment] 2018-11-06 14:45
Also in the wifiphisher interface where I see who connects to the fake WiFi does not show me which pages the victims connect to

**Comment by azamet90** [comment] 2018-11-07 16:37
on me it appears on some sites on some not for example on yahoo or apple.com is working which is https site but not on google or facebook.com which is https too

**Comment by totonda** [comment] 2018-11-07 20:52
But it does not directly load the index.html to perform the phishing.
On the phone, when I connect to the fake wifi, I receive "no Internet connection" and before, when I connected you showed "access to this wifi" and when you clicked it opened the phishing page, in this case the facebook .
It does not load the false page directly. As there is no http://10.0.0.1

**Comment by totonda** [comment] 2018-11-08 23:49
solution??

**Comment by BinJeremy** [comment] 2018-11-09 02:41
I need a solution :(

**Comment by totonda** [comment] 2018-11-10 13:17
Fluxion is good for FAKE AP attack?

**Comment by azamet90** [comment] 2018-11-10 13:58
> Fluxion is good for FAKE AP attack?

absolutely! i was having same problem like yours and my all problems was fixed on fluxion but i was having another problems then i did fresh install of kali linux then i used the wlan0 only for handshake jammer tracking etc and wlan1 for AP and it works without error. now is the problem that i cant create AP on wlan0 but for me was important to create AP with alfa wifi adapter wich is on wlan1 pls try it but the 5.6 version you will love it

**Comment by just-programming** [comment] 2018-11-10 19:40
I have the same problem!

**Comment by totonda** [comment] 2018-11-12 00:42
I understand, but I check it with my phone and other phones that I have, where they used to be and now they do not go anymore. Directly wifiphisher does not walk, it does not take that to that popup tab where is the phishing page
@sophron

**Comment by just-programming** [comment] 2018-11-12 06:40
> @totonda
> 
> I know that you copied the syntax of the command from the `README` page. However, it did not make sense. If you do not load any extensions (with --noextensions), the "Known Beacons" (-kB) will not run even if you asked for it. The README was updated accordingly.
> 
> Regarding your issue, I'm not sure I understand where the problem is. What exactly were you expecting to happen and what happened?
> 
> A few things to notice:
> 
>     * If your Evil Twin has no Internet access, the victim device will notify the user about that.
> 
>     * Most devices (e.g. those running Android) will throw a pop-up and prompt the victim to the captive portal (see phishing page). If you connect to the same Evil Twin again, this may not happen.
> 
>     * There is something called HSTS. You won't get redirected to every HTTPS site. Please see the [FAQ](https://wifiphisher.readthedocs.io/en/latest/faq.html).
> 
> 
> Based on that,
> 
> > I receive "no Internet connection" and before, when I connected you showed "access to this wifi" and when you clicked it opened the phishing page, in this case the facebook .
> 
> This won't always popup as I explained earlier. It may not happen if you visit the same Evil Twin. It also depends on the running software.
> 
> > It does not load the false page directly. As there is no http://10.0.0.1
> 
> What will happen if you manually visit http://neverssl.com?
> 
> Logs with `--logging` would also be helpful.

I have the same problem but I am not running Android 9. I tried it with different phones and it didn't work. I am running Parrot OS and it stopped working after the last update. I tried it on Ubuntu Mate 16.04 and it works fine, the window pops up as it did before.
The internet connection is not the problem, because I found out when you connect the AP to the internet the login page is never shown and without internet, it works better and there is no message telling the client that there is no internet connection. If it helps I can post the logging but there are no errors in it, it looks the same as before. After the update, I tried reinstalling it but it still doesn't work.

**Comment by sophron** [comment] 2018-11-12 10:43
I'm trying to understand exactly what you are describing. When the phone connects to the rogue AP, does it display a notification "Sign into Wi-Fi network"? Like this <a href="https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/5050023654/original/Screenshot_2015-07-09-10-04-25.jpg?1449521621">one</a>?

If not, is that the issue that you are describing?

**Comment by BinJeremy** [comment] 2018-11-12 10:45
> I'm trying to understand exactly what you are describing. When the phone connects to the rogue AP, does it display a notification "Sign into Wi-Fi network"? Like this [one](https://s3.amazonaws.com/cdn.freshdesk.com/data/helpdesk/attachments/production/5050023654/original/Screenshot_2015-07-09-10-04-25.jpg?1449521621)?
> 
> If not, is that the issue that you are describing?

It only reported that the fake AP had no internet connection

**Comment by BinJeremy** [comment] 2018-11-12 10:49
It will look like this

[https://scontent.fdad3-1.fna.fbcdn.net/v/t1.15752-9/45937845_306828693379281_8016144845498220544_n.jpg?_nc_cat=102&_nc_ht=scontent.fdad3-1.fna&oh=873366d3329d3dba5d07c0caeb191030&oe=5C7AF7FF](url)

**Comment by BinJeremy** [comment] 2018-11-12 10:52
![inked46003588_263452454368189_5482438307809853440_n_li](https://user-images.githubusercontent.com/36375220/48342942-9ba2de00-e6a3-11e8-9b77-a324f50060bd.jpg)
Like this image 🍡

**Comment by sophron** [comment] 2018-11-12 11:01
Okay. And what were you expecting to see instead?

**Comment by sophron** [comment] 2018-11-12 11:04
If you use <a href="https://github.com/wifiphisher/wifiphisher/releases/tag/v1.4">v1.4</a> do you still receive the same message?

**Comment by BinJeremy** [comment] 2018-11-12 11:04
> Okay. And what were you expecting to see instead? Were you expecting the "Sign into Wi-Fi network" message?


I want it to say "Sign into Wi-Fi network" but no notifications are shown :)

**Comment by sophron** [comment] 2018-11-12 11:12
I'll have a look to see why this may happen. Until then, if you can use v1.4 and let me know if it worked there, that would be great.

**Comment by BinJeremy** [comment] 2018-11-12 11:20
> I'll have a look to see why this may happen. Until then, if you can use v1.4 and let me know if it worked there, that would be great.

I using wifiphisher 1.4T , with Samsung , Xiaomi ... device it will be working , but android Pie it not

**Comment by sophron** [comment] 2018-11-12 11:58
v1.4 is different than v1.4GIT. Please make sure you have used both and still encounter the same issue.

**Comment by totonda** [comment] 2018-11-12 12:38
@sophron 
Yes, I use version 1.4 and I stop working after an update of Kali. The problem that describes you @BinJeremy is what happens to me the difference that happens to me in kali linux

**Comment by just-programming** [comment] 2018-11-12 12:58
I guess the last updates broke something wifiphisher is using, because it was after the update and since Kali and Parrot are Debian based and Ubuntu is not in my opinion this is where the problem is.

**Comment by BinJeremy** [comment] 2018-11-14 03:30
How to using wifiphisher ver 1.4 :(

**Comment by sophron** [comment] 2018-11-15 13:35
I'll try to see if something changed and we cannot trigger the "Sign into Wi-Fi network" pop-up box.

**Comment by JetseVerschuren** [comment] 2018-11-27 08:57
> I don't understand the language in the second screenshot to explain the difference.

The second screenshot is in German and roughly translates to `This Wi-Fi network has no internet access. Other Wi-Fi networks are available. Change networks?`

**Comment by totonda** [comment] 2018-11-27 19:49
Not Solution

**Comment by BinJeremy** [comment] 2018-11-27 19:52
Haizzz

**Comment by totonda** [comment] 2018-12-02 00:06
> @just-programming @BinJeremy,
> 
> I updated my Kali box and ran the latest version. I don't see any specific issues. What we are doing is emulating a captive portal mechanism. Specifically, we put some firewall rules, redirect everything localhost and resolve everything locally. All of these appear to be working okay.
> 
> On Android (Oreo), I'm getting a notification that "Internet access may not be available". That looks correct to me. The same thing would happen to a legit public hotspot with a captive portal mechanism.
> 
> > One is Ubuntu (first) where it opens directly and the other is from Parrot OS (second). Both are the version from GitHub and freshly installed. The version from the website gives loads of errors so I couldn't try it!
> 
> I don't understand the language in the second screenshot to explain the difference.
> 
> > I using wifiphisher 1.4T , with Samsung , Xiaomi ... device it will be working , but android Pie it not
> 
> Different OS may react differently. One version may say that there is no Internet access, other may say that there may be Internet access. I don't think there's anything we can do about that from our side as long as we are imitating a legit captive portal mechanism.

**Comment by totonda** [comment] 2018-12-02 00:07
"Specifically, we put some firewall rules, redirect everything localhost and resolve everything locally. All of these appear to be working okay." how did you do this?
pls @sophron

**Comment by blackHatMonkey** [comment] 2018-12-03 22:48
@totonda you can take a look at this function https://github.com/wifiphisher/wifiphisher/blob/e694589ad869bae5df8f6a2b49a543c63f66e2c0/wifiphisher/common/firewall.py#L33-L51

**Comment by totonda** [comment] 2018-12-04 23:55
It is impossible no longer works the wifiphisher in kali linux.

**Comment by totonda** [comment] 2018-12-05 13:55
I have to put those firewall rules before starting wifiphisher?

**Comment by totonda** [comment] 2018-12-05 14:12
@BinJeremy @sophron

**Comment by rafaleon69** [comment] 2019-02-10 23:07
I have something to add that I just discovered today. The reason wifiphisher may not work for some is because of iptables .1.8.*, downgrading to iptables 1.6.2 fixes the issue.

**Comment by pendok99** [comment] 2019-02-18 19:36
My problem same with yours..

I tried connect to fake ap using my smartphone there are no notification about to sign in to this network..

Then manually go to browser no sign in page are shown and said 'no internet connection'

This happen to me on wifiphisher 1.4 from github clone installing to kali linux 2018.4

My research, When tried to connect two or three times to fake ap, everything is work and sign in page also appeared..

Do you expect the victim want to try to connect to fake ap again?

My guess is no because everyday i running wifiphisher past 1month no any victim traps on my fake ap..

Please fix the bugs and i waiting for the next update.

**Comment by mmomasters** [comment] 2019-03-08 23:25
@ghost any ideas on how to downgrade on kali pi ?

**Comment by sophron** [comment] 2019-03-18 15:10
I pushed a commit yesterday that fixes this.

The problem was the latest version of Android which now detects a captive portal in a different way. In order to solve this, there are some addresses that Wifiphisher now resolves to their real IP (e.g. www.google.com).

The result is even better than before. The latest version of Android will automatically open the phishing page to the victims as soon as it knows that this is a captive portal.

Let me know if you still encounter any issues.

**Comment by N2Network** [comment] 2019-03-18 19:05
@sophron works! I was hoping you could explain the fix and what changes were made so I can better understand it technically how this was resolved.

**Comment by sophron** [comment] 2019-03-19 17:46
In our previous set-up, we used to i) DNS resolve all domain names to localhost and ii) redirect all traffic to localhost. This was enough to trigger the captive portal on modern operating systems.

However, in the latest version of Android this stopped working. Apparently, Android Pie expects to resolve the domain names to their real addresses successfully in order to prove that Internet connectivity is available.

In our current set-up we are still resolving all domains to localhost, except from "google.com" where we resolve to its public address (216.58.192.174). That way we trick the mobile device to think that we do have Internet connectity and eventually trigger the captive portal window.

You can see the relevant commit here: https://github.com/wifiphisher/wifiphisher/commit/c27c2ab1ef9c5c3aad6f9643acb9170cf2c45a73

**Closed by sophron** 2019-03-19 17:46 UTC
Labels: bug :bug:

**Comment by Rahulthakur376** [comment] 2019-03-22 06:41
> > Okay. And what were you expecting to see instead? Were you expecting the "Sign into Wi-Fi network" message?
> 
> I want it to say "Sign into Wi-Fi network" but no notifications are shown :)

Same Problem Me tooo bro. Please solve this issue. A big problem. I used 4 5 devices but not shown on any android. and tried all version of fluxion. But 'Sign into Network' not shown on any android. Please anyone solve this issue I will be grateful.

**Comment by sophron** [comment] 2019-03-24 16:44
@Rahulthakur376 We fixed that recently. Are you sure you are using the latest revision?

**Comment by Rahulthakur376** [comment] 2019-04-04 04:20
@sophron I tried all fluxion from new to oldest but sign into network not shown in any android device. I also updated my kali repo and updated all program that are need to run fluxion but also i Fail . Please solve sign into network issue. Then i thought that it my kali linux problem so i install parrot and also tried ubuntu but it didnt solved. Please solve issue fluxion

**Comment by Crossik9** [comment] 2021-01-25 12:04
Any update? Same problem on Debian, pumpkin works fine.

**Comment by Anomaly2531** [comment] 2021-07-14 06:38
Hi I figured it out actually. What was happening is that there was a process running on port 53 when I tried to connect to my AP which is why one of my devices could not connect to the fake AP. This was because it could not receive an ip address. (idk if that makes sense) however,
this is what I did: 

I checked if anything was listening to port 53
1.lsof -Pn +M | grep ':53 (LISTEN)'
Out put showed that there was something running even while wifiphisher was not running. I guess its probably Ngrok or some other server that I hosted. 

to kill these processes i did:
2. sudo systemctl disable systemd-resolved.service
3. sudo systemctl stop systemd-resolved

It worked for me I hope that works!

**Comment by JetseVerschuren** [comment] 2021-07-15 21:18
You are referring to `systemd-resolved`, that is an internal DNS cache. To make sure every application/service is compatible, they set up a local/internal DNS server, and pointed to it with `/etc/resolv.conf`. If you want to run a custom DNS server, you have to disable that first. Once disabled, local DNS will break, until you start your own server (assuming it has passthrough enabled).

**Comment by sophron** [comment] 2021-07-15 21:29
Interesting. I found this which seems relevant: https://unix.stackexchange.com/questions/304050/how-to-avoid-conflicts-between-dnsmasq-and-systemd-resolved

We should have a check somewhere to make sure nothing listens to port 53.
