### ISSUE TITLE
error in code of latest version?

### ISSUE THREAD

**Issue by MrAeon** [wifiphisher/wifiphisher#613] opened 2017-05-14 16:02 UTC
Not gonna lie, i'm a total noob but i'm learning - slowly. 

```bash
Using wifiphisher throws up this error: 
P requests: 
[*] GET request from 10.0.0.35 for http://api.bing.com/osjson.aspx?query=google.&language=en-GBcom&language=en-GB
[*] GET request from 10.0.0.35 for http://api.bing.com/osjson.aspx?query=google.com&language=en-GB&language=en-GB
[*] GET request from 10.0.0.35 for http://google.com/m/osjson.aspx?query=google.com&language=en-GB&language=en-GB
[*] POST 10.0.0.35 'wfphshr-wpa-password=kfiiemcjao'/m/osjson.aspx?query=google.com&language=en-GB&language=en-GB
[*] GET request from 10.0.0.35 for http://google.com/index.htmlspx?query=google.com&language=en-GB&language=en-GB
    return fn(*args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 511, in _handle_events
    self._handle_read()
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 1344, in _handle_read
    self._do_ssl_handshake()
  File "/usr/lib/python2.7/dist-packages/tornado/iostream.py", line 1264, in _do_ssl_handshake
    self.socket.do_handshake()
  File "/usr/lib/python2.7/ssl.py", line 840, in do_handshake
    self._sslobj.do_handshake()
error: [Errno 0] Error
```

There doesn't seem to be any way to quit, either. Hitting esc does nothing and ctrlC seems like a 'hard' exit - doesn't restart my wifi services either..?

**Comment by blackHatMonkey** [comment] 2017-05-14 16:06
Hi @MrAeon This is a duplicate of #439.

**Closed by blackHatMonkey** 2017-05-14 16:06 UTC
Labels: duplicate
