### ISSUE TITLE
Stuck after Cleared leases

### ISSUE THREAD

**Issue by Anaprofen** [wifiphisher/wifiphisher#372] opened 2016-12-14 12:39 UTC
When running wifiphisher, after reaching:

"Cleared leases, Started DHCP, set up iptables" 

I lose connection to my router and network manager is turned off. I have to exit the program and restart the service.

Using the latest version on Kali.

**Comment by GRA0007** [comment] 2016-12-26 00:37
I'm having the same problem. #280 seems to be the same, but reading it didn't help me at all.

**Comment by niakova** [comment] 2016-12-31 13:26
Same- I have three wifi cards, wifiphisher works perfect with both alpha cards however trying to find a work around to leave my third card connected to internet for remote ssh

**Comment by sophron** [comment] 2017-01-01 14:06
Hi guys,

This feature is on our roadmap. I believe I'll push it during the month.

**Comment by GRA0007** [comment] 2017-01-01 14:07
Awesome. Looking forward to it.

**Comment by laozi999** [comment] 2017-01-10 05:09
You are much, MUCH better off using **wicd** and ditching Network Manager.

`sudo apt-get install wicd`

Network Manager saves your **ACTUAL MAC ADDRESS**, and then makes sure it is used persistently when connecting to a network, **EVEN AFTER YOU USE MACCHANGER!**

There is a way to change your mac address inside network manager, but it seems to force you to at least connect once with your real mac address before allowing you to change your identity. (Open network-manager, click on the settings icon of your WiFi, click on the **identity** tab, and choose a new (and valid) mac address.

**AFTER YOU'VE INSTALLED WICD**, you can safely remove Network Manager like so:

`sudo apt-get remove network-manager && sudo apt-get remove NetworkManager`

(I forgot the actual name, so just try both)

Now you can open wicd and connect with your spoofed mac address, without worrying about a thing :)

**Comment by blackHatMonkey** [comment] 2017-02-17 23:18
Hi @Anaprofen Can you please confirm if the issue is present or not?

**Comment by blackHatMonkey** [comment] 2017-03-08 13:41
Since there hasn't been any problems after this bug fix, I'm closing this issue. Feel free to open if needed.

**Closed by blackHatMonkey** 2017-03-08 13:41 UTC
Labels: bug: reproducible, in progress
