### ISSUE TITLE
Wifiphisher 1.3GIT any method errors

### ISSUE THREAD

**Issue by mostApi** [wifiphisher/wifiphisher#659] opened 2017-06-30 13:45 UTC
Wifiphisher 1.3GIT on Kali Linux 2017
Sorry, so bad English...

Use and select Firmware Upgrade Page template or Network Manager Connect template
When user connection a new fake AP - I get a lot of mistakes in Wifiphisher script

In code: 
```Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 470, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 458, in start
    curses.wrapper(tui_main_object.gather_info, main_info)
  File "/usr/lib/python2.7/curses/wrapper.py", line 49, in wrapper
    curses.nocbreak()
_curses.error: nocbreak() returned ERR
```
In Screen Shot when Wifiphisher script running: 
![1](https://user-images.githubusercontent.com/29798398/27738082-ee93aa34-5d99-11e7-9f28-26e2d343e4f0.png)

That is how it should be? Help!

**Comment by anakin1028** [comment] 2017-06-30 13:51
We have seen this issue in #439. Unfortunately, we don't have solution for this yet. Is it easy to reproduce this bug?

**Comment by mostApi** [comment] 2017-06-30 13:57
> is it easy to reproduce this bug? - Yes.
What to do?

**Comment by blackHatMonkey** [comment] 2017-07-02 19:05
@mostApi I think this is another duplicate of #439.

**Closed by blackHatMonkey** 2017-07-02 19:05 UTC
Labels: duplicate
