### ISSUE TITLE
AttributeError: 'NoneType' object has no attribute 'eloop_terminate'

### ISSUE THREAD

**Issue by stefjoe12** [wifiphisher/wifiphisher#683] opened 2017-07-24 08:59 UTC
Hello guys,

I installed wifiphisher on my kali machine. Installed everything i need. When i run the following cmd i get this traceback error:

```
root@localhost:~/wifiphisher# wifiphisher --nojamming -aI wlan1 --essid "FREE WI-FI" -p oauth-login
[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-07-24 10:41
[+] Selecting wlan1 interface for creating the rogue Access Point
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:e7:ff:cf
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[+] Captured credentials:
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 777, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 721, in start
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 504, in stop
    self.access_point.on_exit()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/accesspoint.py", line 186, in on_exit
    self.hostapd_object.stop()
  File "/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd_controller.py", line 317, in stop
    self.hostapd_lib.eloop_terminate()
AttributeError: 'NoneType' object has no attribute 'eloop_terminate'

**Version**: commit a15a2984edf4287f50b12320eb79d46cfe93ead5

**Description**: 
root@localhost:~/wifiphisher# iwconfig
r_rmnet_data6  no wireless extensions.

sit0      no wireless extensions.

rmnet_data7  no wireless extensions.

lo        no wireless extensions.

r_rmnet_data5  no wireless extensions.

rmnet_data4  no wireless extensions.

dummy0    no wireless extensions.

wlan1     no wireless extensions.

r_rmnet_data4  no wireless extensions.

rmnet_data3  no wireless extensions.

wlan0     Qcom:802.11n  ESSID:off/any  Nickname:""
          Mode:Managed  Channel:0  Access Point: Not-Associated
          Bit Rate:0 kb/s   Tx-Power=0 dBm
          RTS thr=117350 B   Fragment thr=8000 B
          Encryption key:off

rmnet_data0  no wireless extensions.

r_rmnet_data3  no wireless extensions.

rmnet_ipa0  no wireless extensions.

p2p0      Qcom:802.11n  ESSID:off/any  Nickname:""
          Mode:Managed  Channel:0  Access Point: Not-Associated
          Bit Rate:0 kb/s   Tx-Power=0 dBm
          RTS thr=117350 B   Fragment thr=8000 B
          Encryption key:off

r_rmnet_data2  no wireless extensions.

bond0     no wireless extensions.

rmnet_data6  no wireless extensions.

r_rmnet_data1  no wireless extensions.

rmnet_data5  no wireless extensions.

r_rmnet_data0  no wireless extensions.

rmnet_data2  no wireless extensions.

r_rmnet_data8  no wireless extensions.

rmnet_data1  no wireless extensions.

r_rmnet_data7  no wireless extensions.



```

**Comment by anakin1028** [comment] 2017-07-24 10:38
Thanks for filling the bug report~ Can you check if the following file exists?

`/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/hostapd-2.6/hostapd/libhostapd.so`

If the file exists can you output the following command?

`python roguehostapd/run.py --help` under the directory: `roguehostapd-1.1.1-py2.7.egg`

Also do you use `python setup.py install` to install wifiphisher?

**Comment by stefjoe12** [comment] 2017-07-24 10:42
Yes, i installed with : python setup.py install

-bash: cd: /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/hostapd-2.6/hostapd/libhostapd.so: No such file or directory

**Comment by anakin1028** [comment] 2017-07-24 10:44
so under the directory:
`/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/hostapd-2.6/hostapd`

you don't have the `.so` file? or you don't even have the hostapd-2.6 folder?

**Comment by stefjoe12** [comment] 2017-07-24 10:48
I think the installer not worked correct.. 

root@localhost:~# cd /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/hostapd-2.6/
-bash: cd: /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/hostapd-2.6/: No such file or directory
root@localhost:~# cd /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/
-bash: cd: /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/roguehostapd/: No such file or directory
root@localhost:~# cd /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/
root@localhost:/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd#

**Comment by anakin1028** [comment] 2017-07-24 10:53
sorry I have a typo for the path : it should be : `roguehostapd/hostapd-2.6/hostapd`

**Comment by anakin1028** [comment] 2017-07-24 11:00
I have tested with my system it works fine.
my output looks like the following:
![1](https://user-images.githubusercontent.com/6182530/28520497-484f24ac-70a2-11e7-84b8-90f1974bf17a.gif)

**Comment by stefjoe12** [comment] 2017-07-24 11:02
root@localhost:/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg# python roguehostapd/run.py --help                                                 usage: run.py [-h] [-ssid SSID] [-c CHANNEL] [-bI BEACON_INT] [-i INTERFACE]                     [-pK WPA_PASSPHRASE] [-kA] [-d {0,1,2}] [-K] [-t] [-v]               optional arguments:                                                                  -h, --help            show this help message and exit                              -ssid SSID, --ssid SSID
                        Specify the service set identifier of the AP                 -c CHANNEL, --channel CHANNEL                                                                            Specify the channel of the AP                                -bI BEACON_INT, --beacon_int BEACON_INT
                        Specify the beacon in millisecond
  -i INTERFACE, --interface INTERFACE                                                                      Interface used to lunch AP
  -pK WPA_PASSPHRASE, --wpa_passphrase WPA_PASSPHRASE                                                      WPA/RSN passhrase                                            -kA, --karma_enable   Enabling karma attack                                        -d {0,1,2}, --debug_level {0,1,2}                                                                        Enabling the verbose debug log: --0 disable all the
                        log--1 enable the debug log, --2 enable verbose debug                              log                                                          -K, --key_data        Include key data in debug messages
  -t, --timestamp       Include timestamps in some debug messages                    -v, --version         Show hostapd version                                       root@localhost:/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg#

**Comment by anakin1028** [comment] 2017-07-24 11:24
I think the shared library of `hostapd` is not built successfully on your system. You don't have libhostapd.so file under `roguehostapd/hostapd-2.6/hostapd`, right?

**Comment by stefjoe12** [comment] 2017-07-24 11:54
Yes, i have it.

root@localhost:/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd-2.6/hostapd# ls
Android.mk      eap_register.d           hostapd.sim_db                            ChangeLog       eap_register.h           hostapd.vlan
Makefile        eap_register.o           hostapd.wpa_psk
README          eap_testing.txt          hostapd_cli.1                             README-WPS      hapd_module_tests.c      hostapd_cli.c
android.config  hlr_auc_gw.c              **libhostapd.so**                           config_file.c   hlr_auc_gw.milenage_db   logwatch
config_file.d   hlr_auc_gw.txt           main.c
config_file.h   hostapd.8                main.d
config_file.o   hostapd.accept           main.o
ctrl_iface.c    hostapd.android.rc       nt_password_hash.c                        ctrl_iface.d    hostapd.conf             wired.conf
ctrl_iface.h    hostapd.deny             wps-ap-nfc.py                             ctrl_iface.o    hostapd.eap_user         wps-ap-nfc.pyc
defconfig       hostapd.eap_user_sqlite
eap_register.c  hostapd.radius_clients                                             root@localhost:/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd-2.6/hostapd#

**Comment by stefjoe12** [comment] 2017-07-24 11:54
Maybe reinstall hostapd?

**Comment by anakin1028** [comment] 2017-07-24 12:11
Can you try the following commands:
```shell
pip uninstall roguehostapd
pip install roguehostapd
```

and then run the `wifiphisher` again?

**Comment by stefjoe12** [comment] 2017-07-24 12:42
Mmmm. Its getting worser i guess. 

root@localhost:/# sudo pip install roguehostapd
Collecting roguehostapd
Exception:
Traceback (most recent call last):
  File "/usr/lib/python2.7/dist-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/lib/python2.7/dist-packages/pip/commands/install.py", line 353, in run    wb.build(autobuilding=True)
  File "/usr/lib/python2.7/dist-packages/pip/wheel.py", line 749, in build
    self.requirement_set.prepare_files(self.finder)
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 380, in prepare_files
    ignore_dependencies=self.ignore_dependencies))
  File "/usr/lib/python2.7/dist-packages/pip/req/req_set.py", line 554, in _prepare_file
    require_hashes
  File "/usr/lib/python2.7/dist-packages/pip/req/req_install.py", line 278, in populate_link
    self.link = finder.find_requirement(self, upgrade)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 465, in find_requirement
    all_candidates = self.find_all_candidates(req.name)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 423, in find_all_candidates
    for page in self._get_pages(url_locations, project_name):
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 568, in _get_pages
    page = self._get_page(location)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 683, in _get_page
    return HTMLPage.get_page(link, session=self.session)
  File "/usr/lib/python2.7/dist-packages/pip/index.py", line 792, in get_page
    "Cache-Control": "max-age=600",
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 501, in get
    return self.request('GET', url, **kwargs)
  File "/usr/lib/python2.7/dist-packages/pip/download.py", line 386, in request
    return super(PipSession, self).request(method, url, *args, **kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 488, in request
    resp = self.send(prep, **send_kwargs)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/sessions.py", line 609, in send
    r = adapter.send(request, **kwargs)
  File "/usr/share/python-wheels/CacheControl-0.11.7-py2.py3-none-any.whl/cachecontrol/adapter.py", line 47, in send
    resp = super(CacheControlAdapter, self).send(request, **kw)
  File "/usr/share/python-wheels/requests-2.12.4-py2.py3-none-any.whl/requests/adapters.py", line 423, in send
    timeout=timeout
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/connectionpool.py", line 643, in urlopen
    _stacktrace=sys.exc_info()[2])
  File "/usr/share/python-wheels/urllib3-1.19.1-py2.py3-none-any.whl/urllib3/util/retry.py", line 315, in increment
    total -= 1
TypeError: unsupported operand type(s) for -=: 'Retry' and 'int'
root@localhost:/#

**Comment by anakin1028** [comment] 2017-07-24 12:58
hmm.. it looks like a network issue and not the problem of the `roguehostapd`
https://stackoverflow.com/questions/37495375/python-pip-install-throws-typeerror-unsupported-operand-types-for-retry

**Comment by D4N0** [comment] 2017-07-24 13:54
The same error for me

[*] Starting Wifiphisher 1.3GIT ( https://wifiphisher.org ) at 2017-07-24 09:48
[+] Sending SIGKILL to wpa_supplicant
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[+] Changing wlan0 MAC addr (BSSID) to 00:00:00:dc:5t:df
[+] Changing wlan1 MAC addr (BSSID) to 00:00:00:e4:f5:4r
[*] Cleared leases, started DHCP, set up iptables
[+] Selecting OAuth Login Page template
[*] Starting the fake access point...
[+] Captured credentials:
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.3', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 777, in run
    engine.start()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 721, in start
    self.stop()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/pywifiphisher.py", line 504, in stop
    self.access_point.on_exit()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/accesspoint.py", line 186, in on_exit
    self.hostapd_object.stop()
  File "/usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd_controller.py", line 317, in stop
    self.hostapd_lib.eloop_terminate()
AttributeError: 'NoneType' object has no attribute 'eloop_terminate'

**Comment by anakin1028** [comment] 2017-07-24 15:08
@stefjoe12 @D4N0 
I think I found the root cause. It looks like the `python setup.py install` didn't rebuild the roguehostapd successfully. We may solve this bug soon.
For now, you can go to the directory as I have mentioned in the previous comment:
`cd /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd-2.6/hostapd` 
And then execute the following commands:
```shell
make clean
make hostapd_lib
```
Then re-run the wifiphisher.

**Comment by mohjarr** [comment] 2017-07-24 16:27
I got the same error .. followed your instructions 

> For now, you can go to the directory as I have mentioned in the previous comment:
cd /usr/local/lib/python2.7/dist-packages/roguehostapd-1.1.1-py2.7.egg/roguehostapd/hostapd-2.6/hostapd
And then execute the following commands:

make clean
make hostapd_lib

Then re-run the wifiphisher.

but I got this error while doing (   make hostapd_lib  )
`compilation terminated.
Makefile:1055: recipe for target '../src/crypto/tls_openssl.o' failed
make: *** [../src/crypto/tls_openssl.o] Error 1
`

**Comment by anakin1028** [comment] 2017-07-24 16:31
It seems that you don't have the libssl library:
try the following command:
`sudo apt-get install libssl-dev`

and then `make hostapd_lib`

**Comment by anakin1028** [comment] 2017-07-26 14:25
Hi all, the bug should be fixed with the newest commit~

**Comment by slavisam87** [comment] 2017-07-26 15:33
@anakin1028 you say the issue 684 is the same but I am getting different errors.

I seem to be missing drivers.
`./src/drivers/driver_nl80211.c:17:31: fatal error: netlink/genl/genl.h: No such file or directory
 #include <netlink/genl/genl.h>
                               ^
compilation terminated.
Makefile:1055: recipe for target '../src/drivers/driver_nl80211.o' failed
make: *** [../src/drivers/driver_nl80211.o] Error 1
`

**Comment by anakin1028** [comment] 2017-07-26 15:41
@slavisam87 
Yes. Does this log get printed when you do `python setup.py install`? If yes, that means you don't have `libnl` installed on your system, so the compilation for `roguehostapd` will fail.

We may add the dependency check for `openssl` and `libnl` for the future.
Maybe you can pull the latest commit to see if wifiphisher work.

**Comment by slavisam87** [comment] 2017-07-26 16:18
The update helped significantly. Knock on wood the issue seems to be gone after getting latest and running setup.py install once more.

**Comment by anakin1028** [comment] 2017-07-26 16:22
@slavisam87 Glad to here about that.
When you do `python setup.py install` do you will it wait for a little more than before? and I would like to know what's your pip version? Thanks

**Comment by slavisam87** [comment] 2017-07-26 16:34
The install did not take too long - few seconds.

pip version:
`root@kali:~/wifiphisher# pip -V
pip 9.0.1 from /usr/lib/python2.7/dist-packages (python 2.7)
`

**Comment by stefjoe12** [comment] 2017-07-27 18:42
@anakin1028 

Sorry for the slow feedback, i can tell you this fix made my day. 

Problem solved!

**Comment by anakin1028** [comment] 2017-07-27 23:32
No problem. Thanks : )

**Comment by StratoMusic** [comment] 2017-07-28 13:21
im getting this error while running attack:

Traceback (most recent call last):
  File "./wifiphisher", line 12, in <module>
    
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 777, in run
    engine.start()
  File "/root/wifiphisher/wifiphisher/pywifiphisher.py", line 766, in start
    curses.wrapper(tui_main_object.gather_info, main_info)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/root/wifiphisher/wifiphisher/common/tui.py", line 610, in gather_info
    is_done = self.display_info(screen, info)
  File "/root/wifiphisher/wifiphisher/common/tui.py", line 733, in display_info
    self.print_http_requests(screen, 14, http_output)
  File "/root/wifiphisher/wifiphisher/common/tui.py", line 634, in print_http_requests
    request_type = match.group(1)
AttributeError: 'NoneType' object has no attribute 'group'


i have tried all of the above but still cant seem to fix

**Comment by anakin1028** [comment] 2017-07-28 13:38
yes, this issue is not relevant with this thread. Thanks for reporting.

**Closed** 2017-08-07 18:13 UTC
Labels: bug: reproducible, solved
