### ISSUE TITLE
Problem with specific Router (HZN)

### ISSUE THREAD

**Issue by mmx83** [wifiphisher/wifiphisher#677] opened 2017-07-17 15:57 UTC
Hello,

Thanks for the nice Tool...Amazing work.

I have tested the Tool with my old Dlink DIR-600 without any Problems ,
i have made a custom template for it, too  , and all works fine.

But now i wanted to check my HorizonBox, thats a HD-Recorder with I-net, TV and Phone.
But every time it gives me an error code out ,, after i use a template ,, 

The Error :
```
HTTP requests: Exception in thread Thread-1:
Traceback (most recent call last):
File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner self.run()
File "/usr/lib/python2.7/threading.py", line 754, in run self.__target(*self.__args, **self.__kwargs)
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/extensions.py", line 279, in _listen stop_filter=self._stopfilter)
File "/usr/lib/python2.7/dist-packages/scapy/sendrecv.py", line 620, in sniff r = prn(p)
File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.3-py2.7.egg/wifiphisher/common/extensions.py", line 245, in _process_packet self._packets_to_send[c_num] += received_packets
KeyError: '13'
```

can maybe anybody help me out? or have an idea?

Thanks

**Comment by anakin1028** [comment] 2017-07-17 16:27
OK. I may know the root cause of this problem. Does your target AP (i.e. HorizonBox) lunch in `channel 13`?

**Comment by anakin1028** [comment] 2017-07-17 16:39
I just push a commit. Can you pull the newest commit and try again?

**Comment by sophron** [comment] 2017-07-17 16:41
We should support 13 channels everywhere. In N. America the max channel standard is 11, but the rest of the world uses 13 channels.

**Comment by mmx83** [comment] 2017-07-17 16:57
hey thanks for the quieck answer ,, yes i live in germany and my box is on channel 13...
i can change it and test it in a few hours..thx

**Comment by anakin1028** [comment] 2017-07-17 23:02
The newest commit should work for you : )

**Comment by blackHatMonkey** [comment] 2017-08-08 21:31
@mmx83 I'm gonna close this issue. You can re-open it if you encounter the error again :smile.

**Closed by blackHatMonkey** 2017-08-08 21:31 UTC
Labels: bug: reproducible
