### ISSUE TITLE
Monitor access point's channel for change

### ISSUE THREAD

**Issue by minanagehsalalma** [wifiphisher/wifiphisher#495] opened 2017-03-04 16:57 UTC
when the router restart the channel change it s an automatic process.. i want the script to auto detect the channel change by running airodump-ng every three minutes or when there are no clients to deauth ... and replace the old channel with the new one and continue the deauth with the new channel.. and put an option to select between airodump-ng every three minutes or when there are no clients to deauth or no.... can you do this ??

**Comment by mcocigra** [comment] 2017-03-04 23:37
This is good if it could be done

**Comment by sophron** [comment] 2017-03-04 23:51
We don't want to depend on `airodump-ng`. We can, however, write our own code and check if the target AP switched channel. This is not trivial, however, as our card needs to hop channels as well. 

I put the "Enchancement" label. This won't be a priority though unless we see more users requesting it.

**Comment by alternatexp** [comment] 2017-03-05 00:10
Use `mdk3` if Wifiphisher's deauthentication doesn't work for you. It is a very aggressive tool.

**Usage:**

`mdk3 <interface> <options>`

**Example:**

`mdk3 wlan2 d -b /path/to/blacklist.txt`

This send deauthentication & disassociation packets to the BSSIDs listed inside your /path/to/blacklist.txt file.

`mdk3 wlan2 d -w /path/to/whitelist.txt`

This send deauthentication & disassociation packets to all BSSIDs except for the ones listed inside your /path/to/whitelist.txt file.

mdk3 automatically hops channel and listens to any interaction to/from the target AP(s).

**Comment by minanagehsalalma** [comment] 2017-03-05 18:05
mdk3 did not work with me after the router channel change although i used mdk3 wlan2 d -b ap mac address .. i must run it manually after the channel change   !!!!!!

**Comment by alternatexp** [comment] 2017-03-06 08:42
`-b blacklist` is more effective when targeting specific BSSID(s).

It sounds like you aren't close to the AP/clients, or your interface's Txpower is too low.

**Comment by minanagehsalalma** [comment] 2017-03-07 09:51
the ap my house  and i use tp-link tl-wn722N  please put the airodump option ...  cause any normally viticm will restart the router when the attack starts. ..  so the attack will be useless...  and will wait for nothing

**Comment by minanagehsalalma** [comment] 2017-03-07 09:51
the ap my house  and i use tp-link tl-wn722N  please put the airodump option ...  cause any normally viticm will restart the router when the attack starts. ..  so the attack will be useless...  and will wait for nothing

**Comment by minanagehsalalma** [comment] 2017-03-07 10:01
sorry i closed the issue mistakenly

**Comment by alternatexp** [comment] 2017-03-08 04:42
@minanagehsalalma 

1. `airmon-ng start wlan0`
2. `mdk3 wlan0 d -b /root/blacklist`

**Comment by minanagehsalalma** [comment] 2017-03-08 20:16
@alternatexp @sophron no bro it is too  slow without specifying channel...  when you put the airodump  option it will auto scan the aps when there's no clients or when the router not found...  and use the ap channel to deauthenticate again ...  so deauthenticate will be more faster and effective  when you specify the channel ......  (@_@)

**Comment by alternatexp** [comment] 2017-03-08 21:24
Too slow? mdk3 is supposed to be extremely fast, and aircrack isn't.

Your Txpower must be far too low, since you claim to be close to the AP.

**Comment by minanagehsalalma** [comment] 2017-03-09 09:34
bro it  is slow without specifying channel...  but  when i specific it it becomes faster...  because it found  the ap...  and send some deauthenticate packets and continue hopping until find it again....  so  i want it to hop the channels when the ap is not found ...  so the airodump option will be faster because it will specific the ap new channel when the ap is not found .......

**Comment by alternatexp** [comment] 2017-03-09 10:03
`bro it is slow without specifying channel... but when i specific it it becomes faster...`

`so the airodump option will be faster because it will specific the ap new channel when the ap is not found .......`

False, this would require the interface to scan (skip deauthing), then once it finds the APs channel it has to reconfigure your interface's channel, then start the deauth again.

Like I said over and over again in numerous posts, mdk3 is very fast and SPAMS deauth packets to all the channels.

**Comment by minanagehsalalma** [comment] 2017-03-09 10:45
bro it s slow because it hops the channels  ..  as i said it send some deauthenticate packets and continue hopping until find it again...  hopping take time and it  take some seconds to deauthenticate the clients...  so they will have a chance to reconnect and not all the clients will be deauthenticated...  while  it must make them disconnected and don't give them  the chance for reconnecting to urge  them to connect to the fake ap..  did you understand  what i want ???

**Comment by minanagehsalalma** [comment] 2017-03-10 17:50
@sophron   the mdk3  worked well now..  i don't the  problem...  but i want wifiphisher to deauthenticate clients  like linset  but add the the airodump option...  so it will use one wifi adapter and will work well ... @alternatexp  i am sorry cause i didn't believe you in the first

**Comment by alternatexp** [comment] 2017-03-11 05:52
mdk3 hops channels faster than you can keep track of...

>  hopping take time

Barely. Stopping the deauth, scanning the air for a new channel(s), reconfiguring the interface's channel, and restarting the deauthenticating takes a lot longer.

mdk3 supports multiple BSSIDs to get deauthenticated at once too.

>  so they will have a chance to reconnect

mdk3 won't give them a chance to reconnect, that is, again:

### IF YOU'RE IN RANGE/YOUR WIRELESS CARD IS STRONG ENOUGH

> @alternatexp i am sorry cause i didn't believe you in the first

No stress mate :)

**Comment by minanagehsalalma** [comment] 2017-03-11 11:19
@alternatexp how long it takes to  (scanning the air for a new channel(s), reconfiguring the interface's channel, and restarting the deauthenticating)....  and it will not be a problem  the ap channel will not be changed  every  five seconds ...???

**Comment by alternatexp** [comment] 2017-03-11 15:33
@minanagehsalalma no, but if there are multiple access points, then yes

mdk3 will always be faster than aircrack

**Comment by minanagehsalalma** [comment] 2017-03-11 15:37
@alternatexp as i said  the aps are near from me...

**Comment by alternatexp** [comment] 2017-03-11 15:39
@minanagehsalalma then I'm sure you have no issues deauthing

**Comment by minanagehsalalma** [comment] 2017-03-11 15:46
@alternatexp yeah.. but  rethink about the airodump option  ......

**Comment by alternatexp** [comment] 2017-03-11 15:57
@minanagehsalalma mdk3 already does exactly what you are asking for...

**Comment by minanagehsalalma** [comment] 2017-03-11 16:09
@alternatexp i am taking about (scanning the air for a new channel(s), reconfiguring the interface's channel, and restarting the deauthenticating)..

**Comment by alternatexp** [comment] 2017-03-11 23:40
I have told you so many times that mdk3 already does this.. It constantly scans the air and watches for channel hops, client -> AP & AP -> communication, it's a gem of a tool...

**Comment by minanagehsalalma** [comment] 2017-03-12 00:17
i didn't  suggest using aircrack to deauth ..  i suggest using airodump-ng to get the router new to deauthenticate with it.....  @alternatexp

**Comment by alternatexp** [comment] 2017-03-12 10:24
@minanagehsalalma airodump-ng is part of the aircrack suite...

I don't want to discuss this any further, mdk3 is the better option for what you ask for.

**Comment by minanagehsalalma** [comment] 2017-03-12 10:37
i know that airodump is part of aircrack suit..  i typed this cause aireplay-ng deauth too...   but sometimes i don't have two wireless adapters ?

**Comment by laozi999** [comment] 2017-03-13 04:30
@minanagehsalalma 

You can't:

1. Host a fake AP using Wifiphisher
2. Change channels to see if there is an AP on the same channel
3. Send deauth/disassocation packets to the specified AP(s)

...at the same time.
our

**Comment by minanagehsalalma** [comment] 2017-03-13 17:29
@laozi999  i used mdk3 mon0 d  -b /root/mina.txt  -c 
without specifying  the channel ....   but sometimes it work  and sometimes it doesn't ......  so i though mdk3 with airodump option to specific the new channel  will fix it  .  ...  like fluxion .....   fluxion doesn't use the airodump to specific the ap new channel...

**Comment by alternatexp** [comment] 2017-03-15 02:36
@minanagehsalalma 
Don't use `-c` option if you're not going to specify any channels..... Read the manual.

**Comment by minanagehsalalma** [comment] 2017-03-15 09:58
i knew..  but -c  without typing any chanel after it....  Enables channel hopping

**Comment by alternatexp** [comment] 2017-03-15 23:40
You're better off specifying the channel(s) for a higher success rate

**Comment by minanagehsalalma** [comment] 2017-03-17 10:16
@alternatexp ok I'd check this..

**Comment by minanagehsalalma** [comment] 2017-03-17 15:14
@alternatexp it doesn't make much differences...  i used mdk3 mon0 d   b /root/mina.txt   -c 1,2,3,4,5,6,7,8,9,10,11,12,13,14

**Comment by laozi999** [comment] 2017-03-18 00:22
@minanagehsalalma you aren't very clear with explaining your issue, what is actually going wrong? I have never had issues with mdk3 before

**Comment by minanagehsalalma** [comment] 2017-03-18 09:25
@laozi999 it take time to start deauthenticating  the clients...  and sometimes  it start deauthenticating but the clients aren't disconnected..

**Comment by minanagehsalalma** [comment] 2017-03-18 17:03
@sophron @alternatexp  i meant in the beginning   `make the jamming interface stop the jamming and start a scan searching for our   target (using BSSID) updating the deauth with the new channel every five minutes without making any changes to the ap interface ...  and make it optional  `

**Comment by laozi999** [comment] 2017-03-20 01:02
@minanagehsalalma 

I think it should scan for channel hops every 3-5 seconds, and I don't think it should be optional as it sounds like this would be the solution to the current deauthentication issues.

**Comment by minanagehsalalma** [comment] 2017-06-27 05:57
@laozi999 i need it because the most of the users does not have a two wifi adapter ... even if they have internal wifi card and usb wifi adapter  often  internal wifi card will not support injection ... like my new labtop ... so it will be better if it can be like linset but with the new channel change automatic detection .....

**Comment by anakin1028** [comment] 2017-07-13 14:54
@sophron 
I think the problem is we only have one card to do both deauthentication and lunch AccessPoint. If we have only one card, after lunching AP we can only deauth the channel the fakeAP stay. 

But the target AP may change the channel. The owner of the target AP may discover that the clients are disconnected so he/she may change the AP's channel. After changing channel, our deauthentication process will fail since we deauth on the original channel.

**Comment by sophron** [comment] 2017-07-13 15:00
@anakin1028 Correct. If we are using only one card, it's not possible to hop channels.

**Comment by minanagehsalalma** [comment] 2017-08-17 03:15
@sophron   @anakin1028  @alternatexp it's possible as i have said  make the jamming interface stop the jamming and start a scan searching for our target (using BSSID)  When the script does not find
clients to deauth  on the old channel . and then restart the attack automatic with the new channel ...  and a new feature play a ringtone when the script doesn't found the ap after multi scans to warn the  script user  that the router has been shutdown

**Comment by anakin1028** [comment] 2017-08-22 11:20
I think for our current framework, this feature should be implemented with two cards. 
Currently we have implemented `-dE` option to death all the BSSIDs with the same ESSID. We can do one more check that if the channel number in the beacon has changed for the target bssid we can deauth on that channel too.

**Comment by yungtravla** [comment] 2017-08-22 13:07
@anakin1028 can -dE also deauth your own rogue AP?

@minanagehsalalma I don't think a ringtone is really necessary, I believe this would be the right setup for a stealthy attack:

1. Specify target BSSID (and scenario) using menu / command line
2. Start the recon module and scan for any clients on the target AP
3. Once recon detects interaction with the target AP:
    1. Send MAC address details to deauth module (which constantly deauths a list) and start deauthing 
    2. **If a phishing scenario is selected:** scan for a 4-way handshake
    (if no phishing scenario and no internet interface is selected: throw error)
4. As soon as this happens, start the rogue AP (because only now it's effective)
5. Verify the password with the captured 4-way handshake and if it's a match:
    1. **If** `-qS` **is enabled:** shutdown
    2. **If** `-iI` **is enabled:** give victim a captive portal lease so his/her packets go through the internet interface intead of the ap interface
    3. If `-iI` **and** `-qS` are **not** enabled: do nothing, let the captive portal page do its thing

The deauther should only ever send packets if a victim tries to interact with the vitim AP, otherwise we're wasting packets. If there is a idle time of say 5 seconds, rescan for the BSSID's channel and repeat the process.

**Comment by anakin1028** [comment] 2017-08-22 13:24
@yungtravla
No. We cannot be one of victims :)

**Comment by yungtravla** [comment] 2017-08-22 21:12
@anakin1028 very well :)

**Comment by minanagehsalalma** [comment] 2017-09-01 09:03
@anakin1028 no @yungtravla is right ... deauthing the bssid will be better than deauthing  ssid cause our rogue AP will have the same ssid . did you get it ? 😏

**Comment by anakin1028** [comment] 2017-09-01 09:17
you are misunderstanding.

We know what the `BSSID` of our rouge AP so if we find the target `ESSID` but this `ESSID` has the same `BSSID` of our rogueAP we'll filter it out.

The basic idea is like the following pseudo code:
```
if ESSID == "TargetDeauth and BSSID != rogueAP's BSSID":
    add to deauth set
```

Providing `-dE` is the new future for `wifiphisher` since some users might want to deauth all the same ESSID at the same time.

**Comment by minanagehsalalma** [comment] 2017-09-01 09:23
@anakin1028  but what if i want to deauth  only one BSSID  !!!!!

**Comment by anakin1028** [comment] 2017-09-01 09:39
if you don't provide the `-dE` option, you still deauth the `BSSID` that you have selected from the ap-selection.

**Comment by anakin1028** [comment] 2017-09-01 09:48
Let me deliberate our deauth schemes:

```
cmd1: wifiphisher : Deauth one BSSID from ap selection
cmd2 : wifiphisher -dE : Deauth ESSID equal to the one selected from ap selection excluding our rogueAP
cmd3 : wifiphisher --essid haha : Deauth all the BSSIDs
cmd4 : wifiphisher --essid haha -dE : Deauth all the BSSIDs whose ESSID equal to haha excluding our rougeAP
```

**Comment by minanagehsalalma** [comment] 2017-09-03 10:09
@anakin1028  `cmd1: wifiphisher : Deauth one BSSID from ap selection` does it hopes channels during Deauth  !!! is it better than mdk3 in Deauth  ?

**Comment by anakin1028** [comment] 2017-09-03 10:54
No. It will not do channel hop. I'm planning to implement it in the next few days with a new option `channel-monitoring`.

**Comment by minanagehsalalma** [comment] 2017-09-09 15:12
@alternatexp   @anakin1028  @sophron  @laozi999 i had noticed  that when i run mdk3 manually it's slow and weak effect and takes time to  start Deauthing aps and some times it doesn't start but when i run it by linset or fluxion  it becomes faster and start immediately and in a more effective way ... so do you guys have any ideas ?

**Comment by anakin1028** [comment] 2017-09-09 15:44
@minanagehsalalma I have implemented this feature in the branch `channel_monitor`. If you have time maybe you can pull the commit on that branch and test with `./wifiphisher -cM`.

About the question: The mdk3 is slow if you manually lunch it.
I guess since mdk3 has to do frequency hopping to find the ap you want to attack and that will take time. I haven't used mdk3 by myself and maybe others can give you more opinions.

**Comment by minanagehsalalma** [comment] 2017-09-21 15:13
@alternatexp  it says error unrecognized arguments: -cM

**Comment by anakin1028** [comment] 2017-09-21 15:26
This PR hasn't been merged and we'll merge this soon. Or maybe you can pull the branch `channel_monitor` to do the test first.

**Comment by minanagehsalalma** [comment] 2017-09-21 15:36
@anakin1028  how can pull the branch ??

**Comment by anakin1028** [comment] 2017-09-21 15:43
you can do by the following commands:
```
git fetch
git checkout -b channel_monitor origin/channel_monitor
```
After test is done, you can checkout to master again by
```
git checkout master
```

**Comment by minanagehsalalma** [comment] 2017-09-21 17:10
@anakin1028 it says  fatal: Not a git repository (or any of the parent directories): .git

i am using kali linux

**Comment by sophron** [comment] 2017-09-26 00:09
@minanagehsalalma You need to move to the git directory. Learn about git essentials: https://try.github.io

**Comment by anakin1028** [comment] 2017-11-15 16:36
@minanagehsalalma this has been implemented on the master branch. You can now just pull the latest commit to do the test.

**Closed** 2017-12-04 09:39 UTC
Labels: enhancement/suggestion

**Comment by crazyalex00** [comment] 2023-02-07 12:38
@minanagehsalalma hello bro

#!/bin/bash

interface=<interface>
bssid=<BSSID>

while true; do
  channel=$(iwconfig $interface | grep Frequency | awk '{print $2}' | cut -d '.' -f 1)
  if [ $channel -ne $previous_channel ]; then
    airodump-ng $interface -c $channel --bssid $bssid &
    pid=$!
    disown $pid
    killall airodump-ng
  fi
  previous_channel=$channel
  sleep 5
done

I know if you dont set ap channel, not running well. I think this bash script will be happy to you :)
Note = You can change sleep time what you want

**Comment by minanagehsalalma** [comment] 2023-02-27 11:36
@crazyalex00 thanks mate it looks really useful 
but i am wondering do i have to save the channel to a file or pass it to a script ?
