### ISSUE TITLE
How to fix this?

### ISSUE THREAD

**Issue by raytafarhan** [wifiphisher/wifiphisher#503] opened 2017-03-07 05:01 UTC
[*] Starting Wifiphisher 1.2GIT at 2017-03-07 11:57
[+] Selecting wlan1 interface for the deauthentication attack
[+] Selecting wlan0 interface for creating the rogue Access Point
[*] Cleared leases, started DHCP, set up iptables
Traceback (most recent call last):
  File "/usr/local/bin/wifiphisher", line 11, in <module>
    load_entry_point('wifiphisher==1.2', 'console_scripts', 'wifiphisher')()
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 743, in run
    access_point = curses.wrapper(select_access_point, mon_iface)
  File "/usr/lib/python2.7/curses/wrapper.py", line 43, in wrapper
    return func(stdscr, *args, **kwds)
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 462, in select_access_point
    display_access_points((screen, box, access_points, total_ap_number, page_number, position))
  File "/usr/local/lib/python2.7/dist-packages/wifiphisher-1.2-py2.7.egg/wifiphisher/pywifiphisher.py", line 619, in display_access_points
    access_point.get_number_connected_clients(), vendor))
UnicodeEncodeError: 'ascii' codec can't encode character u'\u2019' in position 4: ordinal not in range(128)

whats wrong? please help

OS : Kali Linux 2.0

**Comment by blackHatMonkey** [comment] 2017-03-07 15:04
Hi @raytafarhan This a duplicate of #496. Please continue the discussion over there.

**Closed by blackHatMonkey** 2017-03-07 15:04 UTC
