### ISSUE TITLE
Error: tornado.application:exception in callback none traceback

### ISSUE THREAD

**Issue by KanabioZ** [wifiphisher/wifiphisher#502] opened 2017-03-06 01:41 UTC
Hi! Have some errors when running 
`wifiphisher -aI wlan1 -jI wlan0 -p firmware-upgrade`

Errors:
```
Error: tornado.application:exception in callback none traceback (most recent call last):n in callback None
File "/usr/lib/python2.7/dist-packages/tornado/ioloop.py", line, in start
handler_func(fd_obj, events)packages/tornado/ioloop.py", line, in start
```
![screenshot from 2017-03-06 03-39-37](https://cloud.githubusercontent.com/assets/26210457/23593983/a32e9d0a-021e-11e7-9cd8-1f9c5bbf5303.png)

Maybe somebody can help too fix it (step by step)?

**Comment by cicina** [comment] 2017-03-06 18:57
Exact same here

**Comment by blackHatMonkey** [comment] 2017-03-07 14:38
@KanabioZ This is a duplicate of #439. Please continue the discussion over there.

**Closed by blackHatMonkey** 2017-03-07 14:38 UTC
