### ISSUE TITLE
Network is down during startup

### ISSUE THREAD

**Issue by falconsy** [wifiphisher/wifiphisher#588] opened 2017-04-25 18:04 UTC
greetings 
dear still error is there after reinstall wifiphisher
u can check PIC down

![capture](https://cloud.githubusercontent.com/assets/25112506/25434251/8ca60e70-2a59-11e7-94c1-16df60ba9730.PNG)
![captusre](https://cloud.githubusercontent.com/assets/25112506/25434252/8cab5826-2a59-11e7-9e3a-f93bc966cd3e.PNG)

kindly your support 

Edited by @blackhatmonkey: fix images

**Comment by blackHatMonkey** [comment] 2017-04-26 12:30
Hi @falconsy The first error I have experienced a lot. In my case it only happens on the first run of `wifiphisher`. Is it the same for you as well?

The second error is a duplicate of #439.

**Comment by falconsy** [comment] 2017-04-26 16:32
for first err yes same u . how i can fix 

and when i run and select the WiFi name this error came

http://gulf-up.com/do.php?img=307803

plz how i can fix because try so many thinks not fixed

**Comment by austin2118ace** [comment] 2017-05-03 21:59
I am having the same error as the first picture; however, it does not resolve after the first run. It persists despite restarts and reruns.

**Comment by blackHatMonkey** [comment] 2017-07-08 12:56
@falconsy Can you check with the latest `Github` version and see if the problem is fixed?

**Comment by blackHatMonkey** [comment] 2017-09-30 18:48
@falconsy A fix has been applied to the latest version. Let us know if the bug is still present in the latest git version.

**Closed by blackHatMonkey** 2017-09-30 18:48 UTC
Labels: bug: reproducible
