### ISSUE TITLE
WIFIPHISHER ERROR PLEASE HELP ME 

### ISSUE THREAD

**Issue by gudi13** [wifiphisher/wifiphisher#650] opened 2017-06-24 01:40 UTC
hello, i install de wifiphisher and when i go open the show this error.

> [*] Starting Wifiphisher 1.3GIT at 2017-06-23 20:04 
> [!] Failed to find an interface with monitor mode
>  [+] Captured credentials: 
> [!] Closing
> please help!!!

**Comment by anakin1028** [comment] 2017-06-24 02:37
@gudi13 this means your adapter card doesn't support the monitor mode.
You can use `iw dev` to see basic information of your adapters and then use `iw phy phy0 info` (i.e. replace phy0 with the one you see in `iw dev`) to see if your card support the monitor mode.

**Comment by gudi13** [comment] 2017-06-24 02:50
hey, ty for the answer.
i work on kali, and i try on terminal use the 

iw dev

 and not work. can you have idea what i do?

**Comment by anakin1028** [comment] 2017-06-24 02:52
can you use `iwconfig`?

**Comment by gudi13** [comment] 2017-06-24 02:53
yes. 

> root@kali:~# iwconfig
> lo        no wireless extensions.
> 
> eth0      no wireless extensions.

*sorry for my english i'm brazilian

**Comment by anakin1028** [comment] 2017-06-24 02:53
check your wlan interface and then do the following:
```shell
ifconfig wlan0 down #change wlan0 to the output of iwconfig
iwconfig wlan0 mode monitor
```

**Comment by gudi13** [comment] 2017-06-24 02:56
root@kali:~# ifconfig wlan0 down
wlan0: ERROR while getting interface flags: No such device

**Comment by anakin1028** [comment] 2017-06-24 02:57
No worries. It seems that you don't have the wireless card, so the tool fails to run.

**Comment by anakin1028** [comment] 2017-06-24 02:58
here's my output: you can see I have the wlan0 interface as a wireless interface

```shell
root@user:~/wifiphisher_master/wifiphisher/bin# iwconfig
wlan0     IEEE 802.11abgn  ESSID:off/any  
          Mode:Managed  Access Point: Not-Associated   Tx-Power=16 dBm   
          Retry  long limit:7   RTS thr:off   Fragment thr:off
          Encryption key:off
          Power Management:off
          
lo        no wireless extensions.

eth0      no wireless extensions.
```

**Comment by anakin1028** [comment] 2017-06-24 03:00
I'll close this issue first and if you still have questions we can still discuss in this thread : )

**Closed by anakin1028** 2017-06-24 03:00 UTC
Labels: question

**Comment by gudi13** [comment] 2017-06-24 03:05
ok, i put this on the terminal on the kali and.

> root@kali:~# /wifiphisher_master/wifiphisher/bin# iwconfig
> bash: /wifiphisher_master/wifiphisher/bin#: No such file or directory

**Comment by anakin1028** [comment] 2017-06-24 03:09
`iwconfig` is a tool to see the available interfaces (i.e. ethernet, wireless,...) on your computer. So the root cause is you need to buy one a wireless adapter card.

**Comment by gudi13** [comment] 2017-06-24 03:13
yes, i using a notebook and have a wirless and i using a adapter card too. so i dont know why doesn't working on kali. i emulatin on virtual box

**Comment by anakin1028** [comment] 2017-06-24 03:22
Do you have a dongle for wifi accessing? I'm not so sure if virtual box can reach the card embeded in the computer.

**Comment by gudi13** [comment] 2017-06-24 03:29
yes, oh i'm so sad now, because its not working hahahaa. sorry take time of you.

**Comment by anakin1028** [comment] 2017-06-24 03:37
No problem :)

**Comment by Marcoslaurenz** [comment] 2021-04-12 03:56
I have the same problem

**Comment by shaikmohammed8** [comment] 2023-10-20 16:35
Starting Wifiphisher 1.4GIT ( https://wifiphisher.org ) at 2023-10-20 22:02
[+] Timezone detected. Setting channel range to 1-13
ERROR:root:The following error has occurred:
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/pywifiphisher.py", line 489, in start
    mon_iface, ap_iface = self.network_manager.get_interface_automatically(
                          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 626, in get_interface_automatically
    monitor_interface = self.get_interface(has_monitor_mode=True)
                        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py", line 615, in get_interface
    raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode))
wifiphisher.common.interfaces.InterfaceCantBeFoundError: Failed to find an interface with monitor mode
[!] Failed to find an interface with monitor mode
[+] Show your support!
[+] Follow us: https://twitter.com/wifiphisher
[+] Like us: https://www.facebook.com/Wifiphisher
[+] Captured credentials:
[!] Closing

**Comment by shaikmohammed8** [comment] 2023-10-20 16:35
i am getting this error

**Comment by leonildo-junior** [comment] 2023-10-31 02:26
tambem estou recebendo esse mesmo erro, comprei um adpador wi-fi tp-link v2/v3, ativei o modo monitor mais mesmo assim retorna esse erro.

**Comment by leonildo-junior** [comment] 2023-10-31 21:25
> Iniciando Wifiphisher 1.4GIT ( https://wifiphisher.org ) em 20/10/2023 22:02 [+] Fuso horário detectado. Configurando o intervalo de canais para 1-13 ERRO:root:Ocorreu o seguinte erro: Traceback (última chamada mais recente): Arquivo "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11. egg/wifiphisher/pywifiphisher.py", linha 489, em start mon_iface, ap_iface = self.network_manager.get_interface_automatically( ^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^^^^^^^^ Arquivo "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/ wifiphisher/common/interfaces.py", linha 626, em get_interface_automatically monitor_interface = self.get_interface(has_monitor_mode=True) ^^^^^^^^^^^^^^^^^^^^^^^^^^^ ^^^^^^^^^^^^^^^ Arquivo "/usr/local/lib/python3.11/dist-packages/wifiphisher-1.4-py3.11.egg/wifiphisher/common/interfaces.py" , linha 615, em get_interface raise InterfaceCantBeFoundError((has_monitor_mode, has_ap_mode)) wifiphisher.common.interfaces.InterfaceCantBeFoundError: Falha ao encontrar uma interface com modo monitor [!] Falha ao encontrar uma interface com modo monitor [+] Mostre seu apoio! [ +] Siga-nos: https://twitter.com/wifiphisher [+] Curta-nos: https://www.facebook.com/Wifiphisher [+] Credenciais capturadas: [!] Fechando

como vc resolveu? estou com o mesmo problema
