### ISSUE TITLE
Duplicate of #477

### ISSUE THREAD

**Issue by zero77** [wifiphisher/wifiphisher#541] opened 2017-03-25 14:39 UTC
wifiphisher is looking really good and the cli is very nice to use now, thanks to the recent development and updates.

So can you please add an update option that if run will automatically check github and install any new updates, instead of manually having to check github and manually update it each time.

Thanks

**Comment by blackHatMonkey** [comment] 2017-03-25 16:26
@zero77 If you install using `pip` you would only need to run:
```bash
[sudo] pip install wifiphisher --upgrade
```

**Comment by zero77** [comment] 2017-03-25 17:41
I was meaning more of a built in option that is shown in the help menu.

**Comment by blackHatMonkey** [comment] 2017-03-25 17:44
@zero77 This is a duplicate of #477. Please see [this](https://github.com/wifiphisher/wifiphisher/issues/477#issuecomment-283447076) comment.

**Closed** 2017-03-26 18:52 UTC
Labels: duplicate
