### ISSUE TITLE
Device Jamming not happening

### ISSUE THREAD

**Issue by mad2kx** [wifiphisher/wifiphisher#475] opened 2017-02-28 19:16 UTC
Hi there, I am using v1.2 on Kali Linux and for some reason wifiphisher does not jam the devices, nor the screen which I have seen on several screenshots "Jamming Devices" does not pop up.

I have tried with several hotspots but it "gets stuck" with the deauth.

DEAUTH Clients: 
MAC1
MAC2
...

DHCP Lease: empty
HTTP: empty

I am using MacBook pro with Single Kali Installation and 2x D-LINK TL-WN7200ND.

I am trying to access the APs with wifiphisher -aI wlan1 -jI wlan2 and then option 2 for network manager

What else do you require me to post to solve this issue?

**Comment by blackHatMonkey** [comment] 2017-02-28 20:17
Hi @mad2kx Are you not able to see the following in your terminal

![](https://camo.githubusercontent.com/574e63c245118a5399ab329f74fa0269c5bc539b/68747470733a2f2f77696669706869736865722e6769746875622e696f2f77696669706869736865722f7373322e706e67)

It looks a bit different in the new version but same structure is present.

**Comment by blackHatMonkey** [comment] 2017-02-28 20:20
Here is an update image
![](https://anonimag.es/i/Screenshot_20170228_1451319d3a6.png)
![](https://anonimag.es/i/Screenshot_20170228_145135e7160.png)

**Comment by mad2kx** [comment] 2017-02-28 21:47
Hi blackHatMonkey. I was just about to upload screenshots but I see the screen from the last post "update image".
Nothing else is happening and after a couple of hours Kali starts to freeze or is getting extremely slow that I have to restart it.

**Comment by blackHatMonkey** [comment] 2017-02-28 21:49
What happens if you connect to it yourself?

**Comment by mad2kx** [comment] 2017-03-01 05:35
The same. Just a list of mac addresses and that's it

**Comment by cicina** [comment] 2017-03-01 09:46
could not it be just because there is no clients to jam? have you tried on your own router if jamming is successful or not?

**Comment by mad2kx** [comment] 2017-03-01 09:53
I have tried with my own router. It just shows the connected MAC addresses but does not jam them.

**Comment by blackHatMonkey** [comment] 2017-03-01 15:13
@mad2kx Can you use `wireshark` to check if any deauthentication packets are being sent or not?

**Comment by mad2kx** [comment] 2017-03-01 18:34
@blackHatMonkey Yes it's sending deauth packets but for some reasons there is no return command or so (don't know how to explain it)

Not sure if this matters: I normally go via aireplay and can deauth the target (or in this case the bssid in question)

**Comment by blackHatMonkey** [comment] 2017-03-01 18:50
@mad2kx Not sure what you mean by `return command` but `Wifiphisher` sends 3 deauthentication packets:
* From access point to the broadcast address
* From access point to each of the discovered client
* From discovered client to access point

To give you an example lets say that the MAC address of the access point is `11:11:11:11:11:11` and it has found one client with the MAC address of `22:22:22:22:22:22` the following packets will be sent:
* `11:11:11:11:11:11` --> `FF:FF:FF:FF:FF:FF`
* `11:11:11:11:11:11` --> `22:22:22:22:22:22`
`22:22:22:22:22:22` --> `11:11:11:11:11:11`

Hopefully this has cleared up any confusion. Let me know if you have any other questions :smile:.

**Comment by mad2kx** [comment] 2017-03-01 18:54
Understood. But it still doesn't jam the target. Any ideas?

**Comment by blackHatMonkey** [comment] 2017-03-01 19:01
@mad2kx Please take a look at the `Why does deauthentication not work?` section of this [page](http://www.aircrack-ng.org/doku.php?id=deauthentication).
>
>

**Comment by mad2kx** [comment] 2017-03-01 19:09
I can deauth via aircrack that's the confusing part. Do you think I can leave wifiphisher in the background and deauth via aircrack to jam the target?

**Comment by blackHatMonkey** [comment] 2017-03-01 19:21
yes you can use the `-nJ` option when running `Wifiphisher` which tells is to not deauthenticate anything.

**Comment by mad2kx** [comment] 2017-03-01 19:39
So I must deauth with aircrack first and then start wifiphisher and choose option 2 for network manager and then wait...?

**Comment by sophron** [comment] 2017-03-01 19:45
Hi @mad2kx,

Are you trying the latest revision on GIthub?

We recently pushed some fixes regarding jamming, but there's definitely room for improvement.

**Comment by blackHatMonkey** [comment] 2017-03-01 19:46
So you would start `Wifiphisher` with the `-nJ` flag and you would continue as if it was a normal run (choose access point, template, etc). When you want to start the deauthentication just start `aircrack` with the interface not used by `Wifiphisher`.

**Comment by mad2kx** [comment] 2017-03-01 20:50
@sophron yes I am using v1.2 

@blackHatMonkey ok doing it that way does not let me deauth the target. I am receiving 0 ACKs from the client and 50 ACKs from AP
Deauth without wifiphisher in the background works.

**Comment by blackHatMonkey** [comment] 2017-03-01 21:02
@mad2kx Using my example above you should run the following command
```bash
 aireplay-ng -0 50 -a 11:11:1:11:11:11 -c 22:22:22:22:22:22 wireless_interface
```
Also make sure you are not using the interface `Wifiphisher` is using by specifying the interface to use by:
```bash
wifiphisher -nJ -aI ap_interface
```

**Comment by mad2kx** [comment] 2017-03-01 21:22
@blackHatMonkey yes that makes sense not to use the same interfaces.

Sending 64 directed DeAuth. STMAC [MAC ADDRESS] [0 | 24 ACKs]

This is the message I receive all the time, regardless if I send 1x DeAuth or 100.

Appr distance to target: 5m.

**Comment by blackHatMonkey** [comment] 2017-03-02 15:02
@mad2kx Can you check to see if you have the same problem when you created an access point(using `hostapd`) with same name and deauthenticate using `aircrack`?

**Comment by mad2kx** [comment] 2017-03-02 16:13
@blackHatMonkey I will try to give you feedback until friday. currently bit swamped with work. bear with me.

**Comment by mad2kx** [comment] 2017-03-02 19:57
@blackHatMonkey I have installed the patch and using wifiphisher alone: nothing is happening. It runs for hours and just copies the target and lists the MAC Addresses which is wants to deauth.

So I restarted wifiphisher with `wifiphisher -nJ -aI ap_interface` followed by aircrack and manually deauthorized the target. created a wonderful 4way handshake. Wifiphisher is running in the background and nothing is moving. Isn't there something supposed to happen now?

**Comment by blackHatMonkey** [comment] 2017-03-02 20:03
@mad2kx Please check out [How it works](https://github.com/wifiphisher/wifiphisher#how-it-works) section in README. It's up to the user to connect to the evil twin access point and give you the credentials.

**Comment by mad2kx** [comment] 2017-03-02 20:26
@blackHatMonkey thanks I will just have to wait then. I will keep you posted.

**Comment by blackHatMonkey** [comment] 2017-03-22 18:40
I'm closing this as it would seem the problem is solved.

**Closed by blackHatMonkey** 2017-03-22 18:40 UTC
